# Side Projects
Short data projects so data notebook doesn't get crowded

In [1]:
# Imports and colors and numbers that won't change
import pandas as pd
import matplotlib.pyplot as plt
import random
import numpy as np
import seaborn as sns
import scipy.stats as stats
#First year of data will not change, last year is not inclusive
min_data_year = 1880
max_data_year = 2026
female_color = 'xkcd:pink'
male_color = 'xkcd:light blue'
default_color = 'xkcd:periwinkle'
default_color2 = 'xkcd:grass green'
colors = ['xkcd:red','xkcd:orange','xkcd:mustard','xkcd:grass green', 'xkcd:light blue','xkcd:cerulean','xkcd:indigo', 
          'xkcd:lavender', 'xkcd:pink', 'xkcd:black', 'xkcd:tan', 'xkcd:grey blue']
generation_starts = {'Missionary' : (1880, 1883), 'Lost' : (1883, 1901), 'Greatest' : (1901, 1928), 'Silent' : (1928, 1946), 'Boomers' : (1946,1965), 'Gen X' : (1965,1981), 'Milennial' : (1981,1997),
                     'Gen X' : (1997,2010), 'Gen Alpha' : (2010,2025), 'Gen Beta' : (2025,2040)}

In [2]:
import functions as fun
fun.init(min_data_year, max_data_year, "names")

In [ ]:
# number of babies in beyond top 1000 dataset
num_in_year = []
for i in range(min_data_year, max_data_year):
    f = fun.get_year_list_one("f", i)
    m = fun.get_year_list_one("m", i)
    num_in_year.append(f["Count"].sum() + m["Count"].sum())
for n in num_in_year:
    print(n)

201484
192688
221533
216945
243460
240854
255316
247391
299474
288946
301401
286673
334374
325223
338690
351020
357483
346957
381454
339233
450258
345812
386733
381200
403484
423923
428451
465390
488648
511224
590711
644279
988061
1137112
1416343
1832427
1934414
2006749
2171111
2110239
2262645
2334507
2289157
2302468
2381614
2333303
2295906
2319346
2260931
2192176
2223305
2104393
2111305
1999456
2076821
2089928
2077595
2130692
2212603
2203464
2302700
2436437
2731880
2822590
2690098
2652945
3195328
3602365
3452526
3484816
3503316
3683696
3797968
3853600
3980666
4015166
4123005
4202087
4134028
4157980
4154261
4142690
4035375
3958585
3887553
3625307
3475638
3394836
3378363
3475190
3606373
3432270
3142852
3016785
3039868
3019218
3034106
3176366
3173696
3326804
3444258
3459237
3507772
3463173
3488665
3569038
3557062
3605616
3695137
3844480
3952585
3895335
3841340
3770400
3717784
3662249
3647307
3625850
3678315
3693973
3780037
3743505
3738396
3802494
3821229
3845147
3956482
3998031
3931088
3820687
3696271
3658318
3657999
3646327
3707226
3701841
3669760
3577417
3517232
3472582
3342625
3390343
3386139
3315158
3343078
3315343

## Babies Named After Wisconsin Cities

In [ ]:
wi_cities_pop = {"Milwaukee": 563531, "Madison": 285300, "GreenBay": 106311, "Kenosha": 99578, "Racine": 78057, "Appleton": 75344, "EauClaire": 72331, "Waukesha": 71461, "Oshkosh": 67242, "Janesville": 66428, "Allis": 59784, "La Crosse": 51049, "Sheboygan": 49624, "Wauwatosa": 48794, "FondduLac": 44469, "Brookfield": 41268, "MenomoneeFalls": 40700, "Berlin": 40302, "Wausau": 40262, "SunPrairie": 39253, "OakCreek": 38373, "Greenfield": 37232, "Beloit": 36633, "Franklin": 36591, "Manitowoc": 34616, "Fitchburg": 34357, "Bend": 32149, "Mount Pleasant": 28184, "Neenah": 27502, "Superior": 26620, "StevensPoint": 26465, "Muskego": 25759, "DePere": 25453, "Mequon": 25329, "Caledonia": 25240, "Watertown": 22617, "Middleton": 22566, "Howard": 21961, "PleasantPrairie": 21802, "Germantown": 21032, "Oconomowoc": 20002}
# above removed directional words and 'new' and 'city' if it was a separate word 'waukesha city' -> 'waukesha'
# also removed South Milwaukee at 20,233
# removed spaces
wi_f = []
wi_m = []
wi_cities = list(wi_cities_pop.keys())
for n in wi_cities:
    name_counts_f = fun.name_counts_years(n.lower(), 'f', min_data_year, max_data_year)[0]
    name_counts_m = fun.name_counts_years(n.lower(), 'm', min_data_year, max_data_year)[0]
    wi_f.append(sum(name_counts_f))
    wi_m.append(sum(name_counts_m))
wi_f = np.array(wi_f, dtype=int)
wi_m = np.array(wi_m, dtype=int)
x = np.arange(len(wi_cities))
fig, ax = plt.subplots(figsize=(14,8))
plt.bar(x, wi_f, color = female_color, label = 'female')
plt.bar(x, wi_m, bottom=wi_f, color = male_color, label = 'male')
plt.xticks(x, wi_cities, rotation = 90)
plt.legend()
plt.xlabel("city")
plt.ylabel("total count (1880-2024)")
plt.title("Number of babies named after Wisconsin cities (> 20,000 pop.)")
plt.ylim(0, 550000)
for i, (f, m) in enumerate(zip(wi_f, wi_m)):
    if f + m > 0:
        label = f"{f} f; {m} m"
        ax.text(i, f + m + 10, str(label), ha='center', va='bottom', fontsize=8, rotation=90)

## Where On a Map Can You Name Your Kid After?

In [ ]:
geo_features = ["coast", "lake", "lakelyn", "lakelynn", "ocean", "river", "brook", "brooke",
                "brooks", "isla", "islay", "rio", "valley", "bay", "delta", "cove", "loch",
                "marsh", "marsha", "sea", "tide", "bayou", "fjord", "mesa", "sierra", "ridge",
                "hill", "knoll", "canyon", "gorge", "ravine", "basin", "cape", "reef", "prairie",
                "savanna", "savannah", "tundra", "glacier", "dune", "meadow", "woods", "forrest",
                "forest", "island", "terra", "beach", "channel", "cliff", "shoal", "rock", "rocky",
                "stone", "crag", "bar", "gorge", "levee", "vale", "alpine", "oasis", "summit",
                "dale", "dell", "glen", "glenn", "glenna", "terrace", "taiga"]
# directions, "new", variations of Guinea, ands separated, saint removed, islands, sierra, united, emirates, san
countries = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua", "Barbuda", 
             "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", 
             "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
             "Bolivia", "Bosnia", "Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", 
             "BurkinaFaso", "Burundi", "CaboVerde", "Cambodia", "Cameroon", "Canada", 
             "CentralAfricanRepublic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", 
             "CostaRica", "Croatia", "Cuba", "Cyprus", "Czechia", "Denmark", "Djibouti", 
             "Dominica", "Ecuador", "Egypt", "Salvador", "Guinea", "Eritrea", 
             "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", 
             "Georgia", "Germany", "Ghana", "Greece", "Greenland", "Grenada", "Guatemala", "Guinea", 
             "Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India",
             "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Ivory", "Jamaica", "Japan", 
             "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos",
             "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", 
             "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", 
             "Marshall", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova",
             "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", 
             "Nauru", "Nepal", "Netherlands", "Holland", "Zealand", "Nicaragua", "Niger", "Nigeria", "Korea",
             "Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", 
             "Papua", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", 
             "Romania", "Russia", "Rwanda", "Kitts", "Nevis", "Lucia", "Vincent", 
             "Grenadines", "Samoa", "Marino", "SaoTome", "Scotland", "Principe", "SaudiArabia", "Senegal", 
             "Serbia", "Seychelles", "Leone", "Singapore", "Slovakia", "Slovenia", 
             "Solomon", "Somalia", "Spain", "SriLanka", "Sudan", "Suriname",
             "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", 
             "TimorLeste", "Togo", "Tonga", "Trinidad", "Tobago", "Tunisia", "Turkey", 
             "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "Arab", "Kingdom", "Britain", "England",
             "States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican", "Venezuela", "Vietnam", 
             "Wales", "Yemen", "Zambia", "Zimbabwe", "Kosovo", "Sahara"]
continent = ["america", "europe", "asia", "africa", "antarctica"]
almost_countries = ["icelyn", "icelynn", "scotlyn", "scotlynn", "irelyn", "irelynn", "thailyn", "thailynn"]
directions = ["north", "east", "south", "west"]
world_cities = ["York", "Angeles", "Chicago", "Houston", "Toronto", "Miami", "Francisco", 
                "Seattle", "Boston", "Atlanta", "Dallas", "Montreal", "Vancouver", "Vegas", 
                "Denver", "Phoenix", "Minneapolis", "Detroit", "Havana", "Panama", "Bogota", 
                "Lima", "Santiago", "Caracas", "London", "Paris", "Berlin", "Madrid", "Rome",
                "Amsterdam", "Barcelona", "Vienna", "Prague", "Warsaw", "Budapest", "Stockholm", 
                "Copenhagen", "Helsinki", "Oslo", "Zurich", "Geneva", "Brussels", "Lisbon", 
                "Athens", "Munich", "Hamburg", "Frankfurt", "Milan", "Naples", "Venice", "Florence", 
                "Edinburgh", "Dublin", "Reykjavik", "Kyiv", "Moscow", "Istanbul", "Ankara", 
                "Sofia", "Sarajevo", "Riga", "Tallinn", "Vilnius", "Minsk", "Yerevan", "Tirana", 
                "Luxembourg", "Dubai", "Riyadh", "Jeddah", "Doha", "Beirut", "Damascus", 
                "Baghdad", "Tehran", "Amman", "Jerusalem", "Muscat", "Sanaa",
                "Cairo", "Lagos", "Nairobi", "Casablanca", "Accra", "Kinshasa", "Algiers",
                "Mumbai", "Delhi", "Karachi", "Colombo", "Tokyo", "Beijing", "Shanghai", "Seoul", 
                "HongKong", "Taipei", "Osaka", "Kyoto", "Wuhan", "Singapore", "Bangkok", "Manila", 
                "Hanoi", "Vientiane", "Bali", "Sydney", "Melbourne", "Brisbane", "Perth", "Auckland",
                "Wellington", "Adelaide", "Monaco"]
planets = ["mercury", "venus", "earth", "mars", "jupiter", "saturn", "uranus", "neptune", "pluto", "moon", "luna"]
named_features = ["everest", "yosemite", "mckinley", "denali", "rainier", "etna", "vesuvius"]
# find average year of each name? and strength so know if its just scattered
# like if a name had a few blips old but is common now then average should be closer to now
# include mountains like everest?
lists = {"geo": geo_features, "country": countries, "continent": continent, 
         "almost_country": almost_countries, "direction": directions, "city": world_cities, 
         "planet": planets, "named_feature": named_features}

In [ ]:
def calculate_spread(name):
    """Takes in name, finds counts by year for each sex
    returns percent difference, number of years with any data, male and female counts,
    and a metric of when the data is centered"""
    # do name counts years
    f_counts, _ = fun.name_counts_years(name, "f", min_y=min_data_year, max_y=max_data_year)
    m_counts, _ = fun.name_counts_years(name, "m", min_y=min_data_year, max_y=max_data_year)
    # do percent difference
    num_f = sum(f_counts)
    num_m = sum(m_counts)
    per_diff = fun.calculate_percent_diff(num_f, num_m)
    # add lists together
    counts = [f_counts[i] + m_counts[i] for i in range(len(f_counts))]
    # find center of data by finding year where sum surpasses current halfway point
    years = sum(1 for i in counts if i != 0)
    half_count = sum(counts) / 2
    s = 0
    center = -1
    for i in range(len(counts)):
        s += counts[i]
        if s >= half_count:
            center = i + min_data_year
            break
    return center, years, per_diff, num_f, num_m

In [ ]:
# iterate over all names
geo_names = pd.DataFrame(columns = ["name", "type", "count", "f_count", "m_count", 
                                    "per_diff", "center_year", "years"])
# make dataframe of values with column for type of name (country, feature)
for l in lists.keys():
    for n in lists[l]:
        center, years, per_diff, num_f, num_m = calculate_spread(n.lower())
        geo_names.loc[len(geo_names)] = [n, l, num_f + num_m, num_f, num_m, 
                                          per_diff, center, years]

In [ ]:
pd.set_option('display.max_rows', None)
geo_names[geo_names["type"] == "country"]

,name,type,count,f_count,m_count,per_diff,center_year,years
68,Afghanistan,country,0,0,0,200.000000,1880,0
69,Albania,country,0,0,0,200.000000,1880,0
70,Algeria,country,32,32,0,200.000000,1994,6
71,Andorra,country,0,0,0,200.000000,1880,0
72,Angola,country,0,0,0,200.000000,1880,0
73,Antigua,country,0,0,0,200.000000,1880,0
74,Barbuda,country,0,0,0,200.000000,1880,0
75,Argentina,country,442,442,0,200.000000,1963,65
76,Armenia,country,163,163,0,200.000000,1921,23
77,Australia,country,350,339,11,187.428571,1932,47
78,Austria,country,17,17,0,200.000000,1992,3
79,Azerbaijan,country,0,0,0,200.000000,1880,0
80,Bahamas,country,0,0,0,200.000000,1880,0
81,Bahrain,country,0,0,0,200.000000,1880,0
82,Bangladesh,country,0,0,0,200.000000,1880,0
83,Barbados,country,0,0,0,200.000000,1880,0
84,Belarus,country,0,0,0,200.000000,1880,0
85,Belgium,country,0,0,0,200.000000,1880,0
86,Belize,country,85,85,0,200.000000,2018,13
87,Benin,country,0,0,0,200.000000,1880,0
88,Bhutan,country,0,0,0,200.000000,1880,0
89,Bolivia,country,5,5,0,200.000000,1990,1
90,Bosnia,country,0,0,0,200.000000,1880,0
91,Herzegovina,country,0,0,0,200.000000,1880,0
92,Botswana,country,0,0,0,200.000000,1880,0
93,Brazil,country,722,653,69,161.772853,2014,32
94,Brunei,country,0,0,0,200.000000,1880,0
95,Bulgaria,country,0,0,0,200.000000,1880,0
96,BurkinaFaso,country,0,0,0,200.000000,1880,0
97,Burundi,country,0,0,0,200.000000,1880,0
98,CaboVerde,country,0,0,0,200.000000,1880,0
99,Cambodia,country,0,0,0,200.000000,1880,0
100,Cameroon,country,0,0,0,200.000000,1880,0
101,Canada,country,54,54,0,200.000000,1995,10
102,CentralAfricanRepublic,country,0,0,0,200.000000,1880,0
103,Chad,country,241767,1039,240728,198.280990,1978,111
104,Chile,country,0,0,0,200.000000,1880,0
105,China,country,4618,4608,10,199.133824,1993,118
106,Colombia,country,0,0,0,200.000000,1880,0
107,Comoros,country,0,0,0,200.000000,1880,0
108,Congo,country,0,0,0,200.000000,1880,0
109,CostaRica,country,0,0,0,200.000000,1880,0
110,Croatia,country,0,0,0,200.000000,1880,0
111,Cuba,country,616,569,47,169.480519,1922,58
112,Cyprus,country,302,21,281,172.185430,2019,21
113,Czechia,country,0,0,0,200.000000,1880,0
114,Denmark,country,5,0,5,200.000000,1970,1
115,Djibouti,country,0,0,0,200.000000,1880,0
116,Dominica,country,2338,2338,0,200.000000,1982,110
117,Ecuador,country,0,0,0,200.000000,1880,0
118,Egypt,country,5546,4726,820,140.858276,2017,42
119,Salvador,country,49788,183,49605,198.529766,1987,130
120,Guinea,country,0,0,0,200.000000,1880,0
121,Eritrea,country,11,11,0,200.000000,2021,2
122,Estonia,country,0,0,0,200.000000,1880,0
123,Eswatini,country,0,0,0,200.000000,1880,0
124,Ethiopia,country,6,6,0,200.000000,2022,1
125,Fiji,country,0,0,0,200.000000,1880,0
126,Finland,country,12,0,12,200.000000,2021,2
127,France,country,1538,1159,379,101.430429,1939,88
128,Gabon,country,0,0,0,200.000000,1880,0
129,Gambia,country,0,0,0,200.000000,1880,0
130,Georgia,country,167019,166290,729,198.254091,1943,146
131,Germany,country,723,517,206,86.030429,2012,41
132,Ghana,country,12,12,0,200.000000,1969,2
133,Greece,country,0,0,0,200.000000,1880,0
134,Greenland,country,0,0,0,200.000000,1880,0
135,Grenada,country,0,0,0,200.000000,1880,0
136,Guatemala,country,0,0,0,200.000000,1880,0
137,Guinea,country,0,0,0,200.000000,1880,0
138,Bissau,country,0,0,0,200.000000,1880,0
139,Guyana,country,0,0,0,200.000000,1880,0
140,Haiti,country,50,50,0,200.000000,2018,8
141,Honduras,country,0,0,0,200.000000,1880,0
142,Hungary,country,0,0,0,200.000000,1880,0
143,Iceland,country,109,98,11,159.633028,2023,9
144,India,country,24017,23990,27,199.550319,1997,146
145,Indonesia,country,83,83,0,200.000000,1997,10
146,Iran,country,1775,416,1359,106.253521,1993,84
147,Iraq,country,0,0,0,200.000000,1880,0
148,Ireland,country,6556,6347,209,187.248322,2009,51
149,Israel,country,72874,1637,71237,191.014628,2003,146
150,Italy,country,2230,2220,10,198.206278,2016,40
151,Ivory,country,23114,14546,8568,51.726227,1987,145
152,Jamaica,country,1569,1532,37,190.567240,1992,53
153,Japan,country,0,0,0,200.000000,1880,0
154,Jordan,country,536795,135599,401196,98.956585,1998,145
155,Kazakhstan,country,0,0,0,200.000000,1880,0
156,Kenya,country,27553,25412,2141,168.918085,1993,73
157,Kiribati,country,0,0,0,200.000000,1880,0
158,Kuwait,country,0,0,0,200.000000,1880,0
159,Kyrgyzstan,country,0,0,0,200.000000,1880,0
160,Laos,country,0,0,0,200.000000,1880,0
161,Latvia,country,0,0,0,200.000000,1880,0
162,Lebanon,country,0,0,0,200.000000,1880,0
163,Lesotho,country,0,0,0,200.000000,1880,0
164,Liberia,country,0,0,0,200.000000,1880,0
165,Libya,country,14,14,0,200.000000,2011,2
166,Liechtenstein,country,0,0,0,200.000000,1880,0
167,Lithuania,country,0,0,0,200.000000,1880,0
168,Luxembourg,country,0,0,0,200.000000,1880,0
169,Madagascar,country,0,0,0,200.000000,1880,0
170,Malawi,country,0,0,0,200.000000,1880,0
171,Malaysia,country,11031,11031,0,200.000000,2015,39
172,Maldives,country,0,0,0,200.000000,1880,0
173,Mali,country,1495,1406,89,176.187291,2011,52
174,Malta,country,55,55,0,200.000000,1920,9
175,Marshall,country,98604,1157,97447,195.306478,1964,146
176,Mauritania,country,0,0,0,200.000000,1880,0
177,Mauritius,country,0,0,0,200.000000,1880,0
178,Mexico,country,0,0,0,200.000000,1880,0
179,Micronesia,country,0,0,0,200.000000,1880,0
180,Moldova,country,0,0,0,200.000000,1880,0
181,Monaco,country,82,33,49,39.024390,2024,4
182,Mongolia,country,0,0,0,200.000000,1880,0
183,Montenegro,country,0,0,0,200.000000,1880,0
184,Morocco,country,165,6,159,185.454545,2020,14
185,Mozambique,country,0,0,0,200.000000,1880,0
186,Myanmar,country,0,0,0,200.000000,1880,0
187,Namibia,country,0,0,0,200.000000,1880,0
188,Nauru,country,0,0,0,200.000000,1880,0
189,Nepal,country,0,0,0,200.000000,1880,0
190,Netherlands,country,0,0,0,200.000000,1880,0
191,Holland,country,11007,7835,3172,84.727900,2015,124
192,Zealand,country,997,72,925,171.113340,2021,24
193,Nicaragua,country,0,0,0,200.000000,1880,0
194,Niger,country,36,25,11,77.777778,1977,5
195,Nigeria,country,810,810,0,200.000000,1999,46
196,Korea,country,298,298,0,200.000000,2006,34
197,Macedonia,country,0,0,0,200.000000,1880,0
198,Norway,country,0,0,0,200.000000,1880,0
199,Oman,country,45,0,45,200.000000,1973,8
200,Pakistan,country,0,0,0,200.000000,1880,0
201,Palau,country,0,0,0,200.000000,1880,0
202,Palestine,country,169,169,0,200.000000,1931,25
203,Panama,country,0,0,0,200.000000,1880,0
204,Papua,country,0,0,0,200.000000,1880,0
205,Paraguay,country,0,0,0,200.000000,1880,0
206,Peru,country,5,5,0,200.000000,2018,1
207,Philippines,country,0,0,0,200.000000,1880,0
208,Poland,country,0,0,0,200.000000,1880,0
209,Portugal,country,0,0,0,200.000000,1880,0
210,Qatar,country,0,0,0,200.000000,1880,0
211,Romania,country,46,46,0,200.000000,1928,8
212,Russia,country,104,104,0,200.000000,2000,17
213,Rwanda,country,10,10,0,200.000000,1951,2
214,Kitts,country,0,0,0,200.000000,1880,0
215,Nevis,country,10,10,0,200.000000,1922,2
216,Lucia,country,59426,59335,91,199.387473,2009,146
217,Vincent,country,364716,1420,363296,198.442624,1971,146
218,Grenadines,country,0,0,0,200.000000,1880,0
219,Samoa,country,0,0,0,200.000000,1880,0
220,Marino,country,2231,0,2231,200.000000,1981,113
221,SaoTome,country,0,0,0,200.000000,1880,0
222,Scotland,country,996,724,272,90.763052,2018,37
223,Principe,country,0,0,0,200.000000,1880,0
224,SaudiArabia,country,0,0,0,200.000000,1880,0
225,Senegal,country,0,0,0,200.000000,1880,0
226,Serbia,country,0,0,0,200.000000,1880,0
227,Seychelles,country,0,0,0,200.000000,1880,0
228,Leone,country,6637,6182,455,172.577972,1920,125
229,Singapore,country,0,0,0,200.000000,1880,0
230,Slovakia,country,0,0,0,200.000000,1880,0
231,Slovenia,country,0,0,0,200.000000,1880,0
232,Solomon,country,38080,11,38069,199.884454,1997,146
233,Somalia,country,114,114,0,200.000000,1993,11
234,Spain,country,0,0,0,200.000000,1880,0
235,SriLanka,country,0,0,0,200.000000,1880,0
236,Sudan,country,10,0,10,200.000000,1982,2
237,Suriname,country,0,0,0,200.000000,1880,0
238,Sweden,country,78,78,0,200.000000,2016,12
239,Switzerland,country,0,0,0,200.000000,1880,0
240,Syria,country,567,567,0,200.000000,2006,42
241,Taiwan,country,913,71,842,168.893757,1986,54
242,Tajikistan,country,0,0,0,200.000000,1880,0
243,Tanzania,country,667,667,0,200.000000,1992,40
244,Thailand,country,184,16,168,165.217391,2014,20
245,TimorLeste,country,0,0,0,200.000000,1880,0
246,Togo,country,0,0,0,200.000000,1880,0
247,Tonga,country,159,159,0,200.000000,1968,17
248,Trinidad,country,9720,4354,5366,20.823045,1950,133
249,Tobago,country,0,0,0,200.000000,1880,0
250,Tunisia,country,596,596,0,200.000000,1978,34
251,Turkey,country,0,0,0,200.000000,1880,0
252,Turkmenistan,country,0,0,0,200.000000,1880,0
253,Tuvalu,country,0,0,0,200.000000,1880,0
254,Uganda,country,58,46,12,117.241379,1975,7
255,Ukraine,country,0,0,0,200.000000,1880,0
256,Arab,country,0,0,0,200.000000,1880,0
257,Kingdom,country,381,0,381,200.000000,2020,17
258,Britain,country,1533,712,821,14.220483,2008,53
259,England,country,320,260,60,125.000000,2016,26
260,States,country,0,0,0,200.000000,1880,0
261,Uruguay,country,0,0,0,200.000000,1880,0
262,Uzbekistan,country,0,0,0,200.000000,1880,0
263,Vanuatu,country,0,0,0,200.000000,1880,0
264,Vatican,country,0,0,0,200.000000,1880,0
265,Venezuela,country,0,0,0,200.000000,1880,0
266,Vietnam,country,0,0,0,200.000000,1880,0
267,Wales,country,38,0,38,200.000000,1930,7
268,Yemen,country,0,0,0,200.000000,1880,0
269,Zambia,country,0,0,0,200.000000,1880,0
270,Zimbabwe,country,5,0,5,200.000000,1981,1
271,Kosovo,country,0,0,0,200.000000,1880,0
272,Sahara,country,4734,4729,5,199.577524,2008,57

In [ ]:
pd.set_option('display.max_rows', None)
country_names = geo_names[geo_names["type"] == "country"]
country_names = country_names[country_names["count"] > 0]
# salvador, holland, zealand, korea, nevis, lucia, vincent, marino, leone, solomon, kingdom
replacements = {"Salvador" : "El Salvador", "Holland" : "Netherlands", "Zealand" : "New Zealand",
                "Korea" : "South Korea", "Nevis" : "Saint Kitts and Nevis", "Lucia" : "Saint Lucia",
                "Vincent" : "Saint Vincent", "Marino" : "San Marino", "Leone" : "Sierra Leone",
                "Solomon" : "Solomon Islands", "Marshall" : "Marshall Islands", "Kingdom" : "United Kingdom", "Ivory" : "Ivory Coast"}
country_names["name"] = country_names["name"].replace(replacements)
country_names

,name,type,count,f_count,m_count,per_diff,center_year,years
70,Algeria,country,32,32,0,200.000000,1994,6
75,Argentina,country,442,442,0,200.000000,1963,65
76,Armenia,country,163,163,0,200.000000,1921,23
77,Australia,country,350,339,11,187.428571,1932,47
78,Austria,country,17,17,0,200.000000,1992,3
86,Belize,country,85,85,0,200.000000,2018,13
89,Bolivia,country,5,5,0,200.000000,1990,1
93,Brazil,country,722,653,69,161.772853,2014,32
101,Canada,country,54,54,0,200.000000,1995,10
103,Chad,country,241767,1039,240728,198.280990,1978,111
105,China,country,4618,4608,10,199.133824,1993,118
111,Cuba,country,616,569,47,169.480519,1922,58
112,Cyprus,country,302,21,281,172.185430,2019,21
114,Denmark,country,5,0,5,200.000000,1970,1
116,Dominica,country,2338,2338,0,200.000000,1982,110
118,Egypt,country,5546,4726,820,140.858276,2017,42
119,El Salvador,country,49788,183,49605,198.529766,1987,130
121,Eritrea,country,11,11,0,200.000000,2021,2
124,Ethiopia,country,6,6,0,200.000000,2022,1
126,Finland,country,12,0,12,200.000000,2021,2
127,France,country,1538,1159,379,101.430429,1939,88
130,Georgia,country,167019,166290,729,198.254091,1943,146
131,Germany,country,723,517,206,86.030429,2012,41
132,Ghana,country,12,12,0,200.000000,1969,2
139,Haiti,country,50,50,0,200.000000,2018,8
142,Iceland,country,109,98,11,159.633028,2023,9
143,India,country,24017,23990,27,199.550319,1997,146
144,Indonesia,country,83,83,0,200.000000,1997,10
145,Iran,country,1775,416,1359,106.253521,1993,84
147,Ireland,country,6556,6347,209,187.248322,2009,51
148,Israel,country,72874,1637,71237,191.014628,2003,146
149,Italy,country,2230,2220,10,198.206278,2016,40
150,Ivory Coast,country,23114,14546,8568,51.726227,1987,145
151,Jamaica,country,1569,1532,37,190.567240,1992,53
153,Jordan,country,536795,135599,401196,98.956585,1998,145
155,Kenya,country,27553,25412,2141,168.918085,1993,73
164,Libya,country,14,14,0,200.000000,2011,2
170,Malaysia,country,11031,11031,0,200.000000,2015,39
172,Mali,country,1495,1406,89,176.187291,2011,52
173,Malta,country,55,55,0,200.000000,1920,9
174,Marshall Islands,country,98604,1157,97447,195.306478,1964,146
180,Monaco,country,82,33,49,39.024390,2024,4
183,Morocco,country,165,6,159,185.454545,2020,14
190,Netherlands,country,11007,7835,3172,84.727900,2015,124
191,New Zealand,country,997,72,925,171.113340,2021,24
193,Niger,country,36,25,11,77.777778,1977,5
194,Nigeria,country,810,810,0,200.000000,1999,46
195,South Korea,country,298,298,0,200.000000,2006,34
198,Oman,country,45,0,45,200.000000,1973,8
201,Palestine,country,169,169,0,200.000000,1931,25
205,Peru,country,5,5,0,200.000000,2018,1
210,Romania,country,46,46,0,200.000000,1928,8
211,Russia,country,104,104,0,200.000000,2000,17
212,Rwanda,country,10,10,0,200.000000,1951,2
214,Saint Kitts and Nevis,country,10,10,0,200.000000,1922,2
215,Saint Lucia,country,59426,59335,91,199.387473,2009,146
216,Saint Vincent,country,364716,1420,363296,198.442624,1971,146
219,San Marino,country,2231,0,2231,200.000000,1981,113
226,Sierra Leone,country,6637,6182,455,172.577972,1920,125
230,Solomon Islands,country,38080,11,38069,199.884454,1997,146
231,Somalia,country,114,114,0,200.000000,1993,11
234,Sudan,country,10,0,10,200.000000,1982,2
236,Sweden,country,78,78,0,200.000000,2016,12
238,Syria,country,567,567,0,200.000000,2006,42
239,Taiwan,country,913,71,842,168.893757,1986,54
241,Tanzania,country,667,667,0,200.000000,1992,40
242,Thailand,country,184,16,168,165.217391,2014,20
245,Tonga,country,159,159,0,200.000000,1968,17
246,Trinidad,country,9720,4354,5366,20.823045,1950,133
248,Tunisia,country,596,596,0,200.000000,1978,34
252,Uganda,country,58,46,12,117.241379,1975,7
255,United Kingdom,country,381,0,381,200.000000,2020,17
256,Britain,country,1533,712,821,14.220483,2008,53
266,Zimbabwe,country,5,0,5,200.000000,1981,1
268,Sahara,country,4734,4729,5,199.577524,2008,57

In [ ]:
import plotly.express as px
fig = px.choropleth(country_names[["name", "count"]],
                    locations='name',          
                    locationmode='country names',
                    color = 'count', # column with the values
                    color_continuous_scale='portland', # this is a nice color
                    labels={'value': 'Value'},
                    range_color=[0, 3000],
                    title='Use of Countries as Names in the US') # title
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0}) # makes it display bigger
fig.show()

In [ ]:
geo_names[geo_names["type"] == "almost_country"]
# add almost countries, and uk countries like scotland, britain

,name,type,count,f_count,m_count,per_diff,center_year,years
273,icelyn,almost_country,303,303,0,200.000000,2023,14
274,icelynn,almost_country,974,974,0,200.000000,2024,19
275,scotlyn,almost_country,1385,1385,0,200.000000,2019,30
276,scotlynn,almost_country,583,583,0,200.000000,2020,24
277,irelyn,almost_country,1594,1594,0,200.000000,2012,29
278,irelynn,almost_country,1740,1740,0,200.000000,2014,28
279,thailyn,almost_country,105,95,10,161.904762,2010,15
280,thailynn,almost_country,21,21,0,200.000000,2016,4

In [ ]:
geo_names[geo_names["type"] == "geo"]

        name type   count  f_count  m_count    per_diff  center_year  years
0      coast  geo     852       87      765  159.154930         2024     12
1       lake  geo    3924      937     2987  104.485219         2008    110
2    lakelyn  geo    3014     2969       45  194.027870         2021     29
3   lakelynn  geo    2652     2652        0  200.000000         2023     24
4      ocean  geo    8233     3822     4411   14.308272         2020     41
5      river  geo   59351    19675    39676   67.399033         2019     46
6      brook  geo   14021    10630     3391  103.259397         1989     95
7     brooke  geo  200521   198491     2030  195.950549         1997    107
8     brooks  geo   59639     1693    57946  188.645014         2019    143
9       isla  geo   58271    58252       19  199.869575         2020    119
10     islay  geo     378      378        0  200.000000         2020     21
11       rio  geo    7812     2282     5530   83.154122         2018     64
12    valley  geo     935      879       56  176.042781         2022     54
13       bay  geo     727      523      204   87.757909         2013     39
14     delta  geo    4476     4368      108  190.348525         1956    142
15      cove  geo    1696      472     1224   88.679245         2022     24
16      loch  geo      90        0       90  200.000000         2019     12
17     marsh  geo     414       11      403  189.371981         1950     55
18    marsha  geo  104442   104191      251  199.038701         1954    116
19       sea  geo      21       10       11    9.523810         1985      4
20      tide  geo      19        0       19  200.000000         2021      3
21     bayou  geo      14        0       14  200.000000         2024      2
22     fjord  geo      15        0       15  200.000000         2020      2
23      mesa  geo     843      843        0  200.000000         2012     43
24    sierra  geo  100866   100597      269  198.933238         1999     82
25     ridge  geo    7911       18     7893  199.089875         2018     46
26      hill  geo     577        0      577  200.000000         1932     70
27     knoll  geo      12        0       12  200.000000         2015      2
28    canyon  geo    4086      259     3827  174.645130         2010     49
29     gorge  geo    2609        0     2609  200.000000         1975    108
30    ravine  geo       5        5        0  200.000000         1990      1
31     basin  geo      13        0       13  200.000000         2020      2
32      cape  geo      24        0       24  200.000000         2023      3
33      reef  geo    1353       63     1290  181.374723         2015     30
34   prairie  geo     501      501        0  200.000000         2016     40
35   savanna  geo   32989    32974       15  199.818121         2003     60
36  savannah  geo  191736   191514      222  199.536863         2005    146
37    tundra  geo      36       36        0  200.000000         1970      6
38   glacier  geo      21       11       10    9.523810         2021      4
39      dune  geo     108        5      103  181.481481         2023      7
40    meadow  geo   12355    12343       12  199.611493         2018     53
41     woods  geo     699       11      688  193.705293         2022     21
42   forrest  geo   54697     1058    53639  192.262830         1958    146
43    forest  geo   18377      593    17784  187.092561         1951    146
44    island  geo     807      698      109  145.972739         2020     27
45     terra  geo   15434    15429        5  199.870416         1983     85
46     beach  geo       5        0        5  200.000000         1915      1
47   channel  geo    1524     1524        0  200.000000         1990     56
48     cliff  geo    9307        0     9307  200.000000         1961    146
49     shoal  geo       5        0        5  200.000000         2022      1
50      rock  geo    2681        0     2681  200.000000         1963     97
51     rocky  geo   29134      447    28687  193.862841         1975    113
52     stone  geo    6831      155     6676  190.923730         2008     53
53      crag  geo       5        0        5  200.000000         1975      1
54       bar  geo      50       23       27   16.000000         2011      8
55     gorge  geo    2609        0     2609  200.000000         1975    108
56     levee  geo     134       84       50   50.746269         2021     11
57      vale  geo     539      340      199   52.319109         2018     27
58    alpine  geo       7        7        0  200.000000         1920      1
59     oasis  geo     383      305       78  118.537859         2019     26
60    summit  geo    1271      247     1024  122.265932         2020     26
61      dale  geo  300043    21887   278156  170.821516         1953    145
62      dell  geo    6552     2544     4008   44.688645         1944    139
63      glen  geo  127054     1348   125706  195.756135         1952    146
64     glenn  geo  250778     2136   248642  196.593003         1953    146
65    glenna  geo   25629    25624        5  199.921963         1942    145
66   terrace  geo     821      107      714  147.868453         1975     61
67     taiga  geo     366       11      355  187.978142         2013     29

In [ ]:
geo_names[geo_names["type"] == "direction"]

      name       type  count  f_count  m_count    per_diff  center_year  years
281  north  direction    407       74      333  127.272727         2013     34
282   east  direction     85        5       80  176.470588         2022      8
283  south  direction     11        0       11  200.000000         2025      2
284   west  direction   3720       28     3692  196.989247         1994    146

In [ ]:
pd.set_option('display.max_rows', None)
city_names = geo_names[geo_names["type"] == "city"]
city_names

,name,type,count,f_count,m_count,per_diff,center_year,years
290,York,city,966,11,955,195.445135,1966,104
291,Angeles,city,3498,3421,77,191.194969,2004,75
292,Chicago,city,175,54,121,76.571429,2022,14
293,Houston,city,18540,436,18104,190.593312,1992,146
294,Toronto,city,49,0,49,200.000000,1974,8
295,Miami,city,349,343,6,193.123209,2012,31
296,Francisco,city,143146,954,142192,197.334190,1992,146
297,Seattle,city,132,127,5,184.848485,2003,19
298,Boston,city,11944,1043,10901,165.070328,2013,103
299,Atlanta,city,699,699,0,200.000000,1999,56
300,Dallas,city,87085,15882,71203,127.050583,1996,146
301,Montreal,city,1113,0,1113,200.000000,1994,56
302,Vancouver,city,0,0,0,200.000000,1880,0
303,Vegas,city,473,145,328,77.378436,2011,30
304,Denver,city,23413,4235,19178,127.647034,1998,135
305,Phoenix,city,40635,16064,24571,41.870309,2016,53
306,Minneapolis,city,0,0,0,200.000000,1880,0
307,Detroit,city,148,0,148,200.000000,1924,22
308,Havana,city,1604,1604,0,200.000000,2016,39
309,Panama,city,0,0,0,200.000000,1880,0
310,Bogota,city,0,0,0,200.000000,1880,0
311,Lima,city,190,190,0,200.000000,1929,30
312,Santiago,city,103965,137,103828,199.472900,2016,141
313,Caracas,city,0,0,0,200.000000,1880,0
314,London,city,54779,44455,10324,124.613447,2013,110
315,Paris,city,42923,33663,9260,113.705939,2005,141
316,Berlin,city,3431,1796,1635,9.385019,2004,114
317,Madrid,city,42,37,5,152.380952,2004,8
318,Rome,city,6075,503,5572,166.880658,2020,112
319,Amsterdam,city,0,0,0,200.000000,1880,0
320,Barcelona,city,0,0,0,200.000000,1880,0
321,Vienna,city,7565,7565,0,200.000000,2017,117
322,Prague,city,0,0,0,200.000000,1880,0
323,Warsaw,city,0,0,0,200.000000,1880,0
324,Budapest,city,0,0,0,200.000000,1880,0
325,Stockholm,city,0,0,0,200.000000,1880,0
326,Copenhagen,city,0,0,0,200.000000,1880,0
327,Helsinki,city,0,0,0,200.000000,1880,0
328,Oslo,city,581,0,581,200.000000,2022,18
329,Zurich,city,143,0,143,200.000000,2018,17
330,Geneva,city,89067,88758,309,198.612281,1929,146
331,Brussels,city,0,0,0,200.000000,1880,0
332,Lisbon,city,16,11,5,75.000000,2017,3
333,Athens,city,218,55,163,99.082569,2019,20
334,Munich,city,0,0,0,200.000000,1880,0
335,Hamburg,city,0,0,0,200.000000,1880,0
336,Frankfurt,city,0,0,0,200.000000,1880,0
337,Milan,city,28165,9557,18608,64.271259,2015,122
338,Naples,city,0,0,0,200.000000,1880,0
339,Venice,city,3232,2946,286,164.603960,1966,130
340,Florence,city,340547,339093,1454,198.292159,1920,146
341,Edinburgh,city,0,0,0,200.000000,1880,0
342,Dublin,city,462,128,334,89.177489,2013,22
343,Reykjavik,city,0,0,0,200.000000,1880,0
344,Kyiv,city,0,0,0,200.000000,1880,0
345,Moscow,city,0,0,0,200.000000,1880,0
346,Istanbul,city,0,0,0,200.000000,1880,0
347,Ankara,city,0,0,0,200.000000,1880,0
348,Sofia,city,186931,186744,187,199.599852,2014,141
349,Sarajevo,city,0,0,0,200.000000,1880,0
350,Riga,city,0,0,0,200.000000,1880,0
351,Tallinn,city,7,7,0,200.000000,2024,1
352,Vilnius,city,0,0,0,200.000000,1880,0
353,Minsk,city,0,0,0,200.000000,1880,0
354,Yerevan,city,0,0,0,200.000000,1880,0
355,Tirana,city,0,0,0,200.000000,1880,0
356,Luxembourg,city,0,0,0,200.000000,1880,0
357,Dubai,city,13,0,13,200.000000,2019,2
358,Riyadh,city,63,0,63,200.000000,2009,10
359,Jeddah,city,0,0,0,200.000000,1880,0
360,Doha,city,164,153,11,173.170732,2009,23
361,Beirut,city,0,0,0,200.000000,1880,0
362,Damascus,city,129,0,129,200.000000,2001,22
363,Baghdad,city,0,0,0,200.000000,1880,0
364,Tehran,city,124,5,119,183.870968,1980,16
365,Amman,city,87,0,87,200.000000,2001,11
366,Jerusalem,city,478,329,149,75.313808,2014,35
367,Muscat,city,0,0,0,200.000000,1880,0
368,Sanaa,city,6146,6146,0,200.000000,2009,44
369,Cairo,city,9999,584,9415,176.637664,2021,40
370,Lagos,city,0,0,0,200.000000,1880,0
371,Nairobi,city,1596,1561,35,191.228070,2021,40
372,Casablanca,city,0,0,0,200.000000,1880,0
373,Accra,city,0,0,0,200.000000,1880,0
374,Kinshasa,city,122,116,6,180.327869,1977,11
375,Algiers,city,0,0,0,200.000000,1880,0
376,Mumbai,city,0,0,0,200.000000,1880,0
377,Delhi,city,0,0,0,200.000000,1880,0
378,Karachi,city,0,0,0,200.000000,1880,0
379,Colombo,city,0,0,0,200.000000,1880,0
380,Tokyo,city,116,89,27,106.896552,2022,9
381,Beijing,city,0,0,0,200.000000,1880,0
382,Shanghai,city,0,0,0,200.000000,1880,0
383,Seoul,city,25,16,9,56.000000,2024,4
384,HongKong,city,0,0,0,200.000000,1880,0
385,Taipei,city,0,0,0,200.000000,1880,0
386,Osaka,city,0,0,0,200.000000,1880,0
387,Kyoto,city,0,0,0,200.000000,1880,0
388,Wuhan,city,0,0,0,200.000000,1880,0
389,Singapore,city,0,0,0,200.000000,1880,0
390,Bangkok,city,0,0,0,200.000000,1880,0
391,Manila,city,214,214,0,200.000000,1898,14
392,Hanoi,city,0,0,0,200.000000,1880,0
393,Vientiane,city,0,0,0,200.000000,1880,0
394,Bali,city,254,212,42,133.858268,2021,18
395,Sydney,city,187700,178296,9404,179.959510,2001,146
396,Melbourne,city,1012,0,1012,200.000000,1927,59
397,Brisbane,city,0,0,0,200.000000,1880,0
398,Perth,city,0,0,0,200.000000,1880,0
399,Auckland,city,0,0,0,200.000000,1880,0
400,Wellington,city,2879,0,2879,200.000000,1949,140
401,Adelaide,city,35007,35007,0,200.000000,2009,146
402,Monaco,city,82,33,49,39.024390,2024,4

In [ ]:
continent_names = geo_names[geo_names["type"] == "continent"]
continent_names = pd.concat([continent_names, geo_names[geo_names["name"] == "Australia"]])
continent_names

,name,type,count,f_count,m_count,per_diff,center_year,years
273,america,continent,13538,13522,16,199.527257,2004,146
274,europe,continent,15,15,0,200.000000,2021,2
275,asia,continent,32687,32491,196,197.601493,1999,67
276,africa,continent,1042,1042,0,200.000000,1985,57
277,antarctica,continent,0,0,0,200.000000,1880,0
77,Australia,country,350,339,11,187.428571,1932,47

In [ ]:
calculate_spread("Oceania")

(2006, 12, 200, np.int64(78), np.int64(0))

In [ ]:
geo_names[geo_names["type"] == "planet"]

        name    type  count  f_count  m_count    per_diff  center_year  years
398  mercury  planet    300       94      206   74.666667         2018     25
399    venus  planet  10057     9956      101  195.982897         1974    139
400    earth  planet     58       46       12  117.241379         2020      8
401     mars  planet   1522      202     1320  146.911958         2021     36
402  jupiter  planet   1749     1099      650   51.343625         2021     23
403   saturn  planet    157      107       50   72.611465         2022     11
404   uranus  planet      5        5        0  200.000000         1969      1
405  neptune  planet     24        0       24  200.000000         2022      3
406    pluto  planet     23        0       23  200.000000         2024      3
407     moon  planet    627      465      162   96.650718         2021     26
408     luna  planet  87834    87715      119  199.458069         2020    133

In [ ]:
geo_names[geo_names["type"] == "named_feature"]

,name,type,count,f_count,m_count,per_diff,center_year,years
409,everest,named_feature,3986,928,3058,106.874059,2020,48
410,yosemite,named_feature,5,5,0,200.000000,1993,1
411,mckinley,named_feature,22884,13098,9786,28.945988,2008,136
412,denali,named_feature,2479,1795,684,89.632916,2013,40
413,rainier,named_feature,920,46,874,180.000000,2012,57
414,etna,named_feature,681,681,0,200.000000,1915,66
415,vesuvius,named_feature,0,0,0,200.000000,1880,0

## Extinct Names
Finding names that used to be used but no longer are at four levels:
- Vulnerable -- names in the top 1,000 from 1924 or earlier with 50 or less per year since 1965
- Endangered -- names in the top 1,000 from 1924 or earlier with 20 or less per year since 1965
- Critically Endangered -- names in the top 1,000 from 1924 or earlier with 10 or less per year since 1965
- Extinct -- names in the top 1,000 from 1924 or earlier with no uses since 1965
This is done at a second cohort for young people

In [75]:
f_top_1000_27 = set() # female names from top 1,000 from 1927 or earlier
m_top_1000_27 = set()
names_25 = {"f" : f_top_1000_27, "m" : m_top_1000_27}
f_top_1000_64 = set() # female names from top 1,000 from 1964 or earlier
m_top_1000_64 = set()
names_45 = {"f" : f_top_1000_64, "m" : m_top_1000_64}
ranks = ["extinct", "crit", "endangered", "vulnerable", "fine"]

In [76]:
for sex in ["f", "m"]:
    for year in range(min_data_year, 1928):
        curr_list = names_25[sex]
        names = fun.get_year_list_one(sex, year)
        names = names.iloc[0:1000]
        curr_list.update(list(names["Name"]))

In [77]:
for sex in ["f", "m"]:
    for year in range(min_data_year, 1965):
        curr_list = names_45[sex]
        names = fun.get_year_list_one(sex, year)
        names = names.iloc[0:1000]
        curr_list.update(list(names["Name"]))

In [78]:
def names_sorter(sex, all_names, min_y=min_data_year, max_y=max_data_year):
    """Checks if the counts of a name across min_y to max_y are less than a number"""
    endangered = pd.DataFrame(columns = ["Name", "Sex", "Rating", "Count"])
    candidate_names = {x : 0 for x in all_names} # 0 = extinct
    for year in range(min_y, max_y): # iterate over years name must follow criteria
        year_list = fun.get_year_list_one(sex, year)
        for n in list(candidate_names): # iterate over names
            if n in list(year_list["Name"]):
                count = year_list[year_list["Name"] == n]["Count"].sum() 
            else:
                count = 0
            current_rank = candidate_names[n]
            if count < 5 and current_rank < 1:
                pass
            elif count <= 10 and current_rank < 2:
                candidate_names[n] = 1 # critically endangered
            elif count <= 20 and current_rank < 3:
                candidate_names[n] = 2 # endangered
            elif count <= 50 and current_rank < 4:
                candidate_names[n] = 3 # vulnerable
            else:
                candidate_names[n] = 4 # fine
    for n, r in candidate_names.items():
        if r != 4:
            total_count = fun.name_counts_simple(n, sex)[0]
            endangered.loc[len(endangered)] = [n, sex, ranks[r], total_count]
    return endangered

In [82]:
endangered_f_65 = names_sorter("f", f_top_1000_27, 1965, max_data_year)

In [83]:
endangered_m_65 = names_sorter("m", m_top_1000_27, 1965, max_data_year)

In [90]:
pd.set_option('display.max_rows', None)
print(endangered_f_65[endangered_f_65["Rating"] == "extinct"].sort_values(by="Count", ascending=False))

             Name Sex   Rating  Count
738         bulah   f  extinct   3027
262         ludie   f  extinct   2687
125         myrle   f  extinct   2405
393    hildegarde   f  extinct   2326
202         emmer   f  extinct   2155
572         eulah   f  extinct   1871
690        goldia   f  extinct   1860
769          myrl   f  extinct   1831
884        mertie   f  extinct   1830
36        burnice   f  extinct   1593
595          odie   f  extinct   1589
342      elfrieda   f  extinct   1487
539          osie   f  extinct   1354
327         olene   f  extinct   1347
216         fleta   f  extinct   1333
622        earlie   f  extinct   1329
298           oda   f  extinct   1324
240        cleone   f  extinct   1320
871       mafalda   f  extinct   1279
773     willodean   f  extinct   1237
508          ozie   f  extinct   1235
284         ether   f  extinct   1214
576        lossie   f  extinct   1189
68          beula   f  extinct   1183
352        hessie   f  extinct   1118
784         ozell   f  extinct   1116
756        berdie   f  extinct   1114
894       flonnie   f  extinct   1065
766    josiephine   f  extinct   1061
290        maymie   f  extinct   1054
764        mossie   f  extinct   1051
826         anner   f  extinct   1037
250          bula   f  extinct   1034
578        mettie   f  extinct   1031
783         orene   f  extinct   1015
714       gladyce   f  extinct   1006
852         buena   f  extinct    987
143        lassie   f  extinct    979
118        zelpha   f  extinct    956
76         birtie   f  extinct    946
148       loretto   f  extinct    923
486           imo   f  extinct    903
195       edmonia   f  extinct    899
466       alverda   f  extinct    891
886        clella   f  extinct    887
87          verne   f  extinct    878
968         frona   f  extinct    873
530        vlasta   f  extinct    873
221         herma   f  extinct    861
364        clydie   f  extinct    853
166       luverne   f  extinct    847
302        vannie   f  extinct    830
516       maebell   f  extinct    823
725         macel   f  extinct    821
856        doshie   f  extinct    799
551        fronie   f  extinct    789
713     bettyjane   f  extinct    788
930         nanie   f  extinct    778
260        eathel   f  extinct    763
266         clyda   f  extinct    758
655          eola   f  extinct    740
154         lutie   f  extinct    735
959        hildur   f  extinct    718
956          orma   f  extinct    699
626         versa   f  extinct    688
56         modena   f  extinct    683
278         besse   f  extinct    671
42           bert   f  extinct    657
161         altie   f  extinct    650
562        lillis   f  extinct    637
351        dellie   f  extinct    634
388          murl   f  extinct    626
670        littie   f  extinct    623
810        girtha   f  extinct    597
305         helma   f  extinct    595
63           lota   f  extinct    586
126      capitola   f  extinct    579
912         gusta   f  extinct    578
717        pinkey   f  extinct    574
248         lular   f  extinct    572
673        dellar   f  extinct    571
23         zilpha   f  extinct    570
876        dossie   f  extinct    568
744         corda   f  extinct    567
779        sister   f  extinct    563
261         cleva   f  extinct    561
344        virdie   f  extinct    555
165      permelia   f  extinct    551
812         dewey   f  extinct    547
380     philomene   f  extinct    544
223        fronia   f  extinct    543
167        dillie   f  extinct    537
217         elgie   f  extinct    529
147         manie   f  extinct    529
381        ermine   f  extinct    522
914        vessie   f  extinct    513
256         ellar   f  extinct    511
334           ura   f  extinct    508
328         pluma   f  extinct    506
628          oral   f  extinct    506
469        mannie   f  extinct    505
108      clotilda   f  extinct    497
798         nobie   f  extinct    496
356        fannye   f  extinct    486
963         eller   f  extinct    481
648         etter   f  extinct    476
130          ruie   f  extinct    470
355           exa   f  extinct    466
425        lockie   f  extinct    464
657        mintie   f  extinct    446
211        ethyle   f  extinct    437
485        beadie   f  extinct    435
204         fleda   f  extinct    432
475          opha   f  extinct    427
21           olie   f  extinct    420
847        parlee   f  extinct    414
800         hasel   f  extinct    400
389        kazuko   f  extinct    398
619         vinie   f  extinct    381
424         oline   f  extinct    377
482        leaner   f  extinct    373
560         lempi   f  extinct    367
427        prudie   f  extinct    354
543         venie   f  extinct    345
484       cliffie   f  extinct    343
540        liller   f  extinct    333
724          beda   f  extinct    328
567         tiney   f  extinct    327
473        gillie   f  extinct    321
158     narcissus   f  extinct    318
0           elfie   f  extinct    316
456         orrie   f  extinct    313
668        tishie   f  extinct    312
802       alwilda   f  extinct    312
679          effa   f  extinct    312
864        clytie   f  extinct    301
789          edla   f  extinct    300
489          luda   f  extinct    276
664          caro   f  extinct    269
16          lemma   f  extinct    262
547        biddie   f  extinct    262
323         litha   f  extinct    261
495          olar   f  extinct    254
869          byrd   f  extinct    253
184         epsie   f  extinct    251
265      josefita   f  extinct    244
213        dezzie   f  extinct    242
404        mirtie   f  extinct    236
461          irva   f  extinct    229
348        orilla   f  extinct    225
103           ica   f  extinct    223
99         hennie   f  extinct    219
728           ota   f  extinct    215
838        manila   f  extinct    214
117        elmire   f  extinct    213
294       fronnie   f  extinct    213
538        clemie   f  extinct    211
15          ragna   f  extinct    201
452         leafy   f  extinct    197
109       pairlee   f  extinct    187
279         arkie   f  extinct    183
347        pallie   f  extinct    176
900       octavie   f  extinct    176
906      birdella   f  extinct    173
402        cornie   f  extinct    172
134        alzina   f  extinct    170
1            loda   f  extinct    166
189        rettie   f  extinct    163
604        clemma   f  extinct    161
288          octa   f  extinct    160
739       aurilla   f  extinct    153
853        thursa   f  extinct    150
132         metha   f  extinct    149
507        sibbie   f  extinct    139
786        ninnie   f  extinct    136
60           orra   f  extinct    129
542       manilla   f  extinct    124
689          bird   f  extinct    121
150        clevie   f  extinct    119
751         gunda   f  extinct    118
647        gustie   f  extinct    106
632          vicy   f  extinct    101
878        caddie   f  extinct     96
954      minervia   f  extinct     95
841        grover   f  extinct     92
857         lidie   f  extinct     91
638         ethie   f  extinct     86
771         tinie   f  extinct     83
825         ednah   f  extinct     75
958        rillie   f  extinct     69
835          oney   f  extinct     61
271         dosia   f  extinct     61
24          affie   f  extinct     60
781       manerva   f  extinct     60
833        siddie   f  extinct     59
480     theodocia   f  extinct     54
524        lurana   f  extinct     48
731        cappie   f  extinct     41
940          ason   f  extinct     41
518      manervia   f  extinct     40
531        neppie   f  extinct     38
361        alwine   f  extinct     25
465        sannie   f  extinct     21
214  francisquita   f  extinct     21
174        alwina   f  extinct     18
458         crete   f  extinct     14
142         franc   f  extinct     10
80         zilpah   f  extinct      9

In [91]:
pd.set_option('display.max_rows', None)
print(endangered_m_65[endangered_m_65["Rating"] == "extinct"].sort_values(by="Count", ascending=False))

           Name Sex   Rating  Count
539       rolla   m  extinct   1306
182        pink   m  extinct   1089
185     luverne   m  extinct   1067
582      perley   m  extinct   1020
499       orvis   m  extinct    940
888       ewald   m  extinct    922
76        elsie   m  extinct    886
359        eino   m  extinct    814
160       hideo   m  extinct    805
896      minnie   m  extinct    787
293     woodroe   m  extinct    784
548     pauline   m  extinct    775
766      selmer   m  extinct    759
161     lucille   m  extinct    750
443      bessie   m  extinct    737
45        clide   m  extinct    718
824        opal   m  extinct    718
736     lilburn   m  extinct    713
976        byrd   m  extinct    709
626      minoru   m  extinct    675
1054     ruffus   m  extinct    674
663    pleasant   m  extinct    629
700    pershing   m  extinct    599
856      nellie   m  extinct    593
240    gertrude   m  extinct    568
403     lillard   m  extinct    541
947       toivo   m  extinct    535
379     pinkney   m  extinct    531
533         ova   m  extinct    528
267       metro   m  extinct    522
801      myrtle   m  extinct    498
392      hattie   m  extinct    494
154         lum   m  extinct    493
894     adelard   m  extinct    488
304       agnes   m  extinct    465
218       orley   m  extinct    459
431     plummer   m  extinct    453
28      fayette   m  extinct    438
508       viola   m  extinct    434
411       eliga   m  extinct    434
48     clemence   m  extinct    418
115      harrie   m  extinct    417
666       aloys   m  extinct    414
652   blanchard   m  extinct    413
1011      mabel   m  extinct    409
870     erastus   m  extinct    407
821      hughey   m  extinct    405
887        vera   m  extinct    398
1051      posey   m  extinct    396
80       doctor   m  extinct    379
688        oley   m  extinct    373
664    coolidge   m  extinct    372
337      fannie   m  extinct    369
778   commodore   m  extinct    368
5         waino   m  extinct    347
388        mell   m  extinct    342
879      burrel   m  extinct    339
407        lula   m  extinct    339
769        eula   m  extinct    332
932       abbie   m  extinct    330
675     needham   m  extinct    328
47         floy   m  extinct    323
167    gottlieb   m  extinct    320
831        harm   m  extinct    320
457       esker   m  extinct    313
1046  littleton   m  extinct    312
364         oda   m  extinct    301
439       leona   m  extinct    294
820     bluford   m  extinct    293
853        wirt   m  extinct    286
400       hymen   m  extinct    285
197        less   m  extinct    281
147       mamie   m  extinct    278
1019      susie   m  extinct    278
233        lola   m  extinct    275
266       oland   m  extinct    274
447       miner   m  extinct    274
17         birt   m  extinct    268
587     council   m  extinct    263
159         ebb   m  extinct    247
610      hezzie   m  extinct    247
556        flem   m  extinct    244
782       press   m  extinct    241
549       ovila   m  extinct    240
350      winnie   m  extinct    228
363       bynum   m  extinct    223
629     blanche   m  extinct    223
730      tatsuo   m  extinct    222
7        beulah   m  extinct    213
916     hjalmer   m  extinct    202
676       alcee   m  extinct    182
354     pearley   m  extinct    178
452       genie   m  extinct    173
876       flora   m  extinct    172
905        thos   m  extinct    166
1026     ignatz   m  extinct    158
612       offie   m  extinct    151
561         ell   m  extinct    144
861       almus   m  extinct    143
406       della   m  extinct    139
583       shoji   m  extinct    134
695       maude   m  extinct    133
611         sie   m  extinct    133
819        dorr   m  extinct    124
413       grove   m  extinct    124
30       greene   m  extinct    121
682       alver   m  extinct    119
649     shafter   m  extinct    119
344       fount   m  extinct    118
244        alta   m  extinct    117
423      emmons   m  extinct    117
144     delphin   m  extinct    116
705        ewin   m  extinct    115
788     hjalmar   m  extinct    115
172      ambers   m  extinct    113
802       elick   m  extinct    113
857      tallie   m  extinct    112
781        bird   m  extinct    109
1040       olof   m  extinct    107
37         dink   m  extinct    107
634         add   m  extinct    102
646      lizzie   m  extinct    102
904        math   m  extinct    100
1032       atha   m  extinct     99
934         abb   m  extinct     96
670     alphons   m  extinct     90
480      ceylon   m  extinct     86
484         ott   m  extinct     84
900        purl   m  extinct     81
340        polk   m  extinct     80
39           ah   m  extinct     74
1039        obe   m  extinct     73
50          fed   m  extinct     72
703      goebel   m  extinct     70
1038       foch   m  extinct     67
826       hence   m  extinct     66
442     hosteen   m  extinct     65
906      boysie   m  extinct     63
923     benjman   m  extinct     58
884    thorwald   m  extinct     54
139      severt   m  extinct     53
858       algot   m  extinct     53
944       virge   m  extinct     52
825        arba   m  extinct     47
799       clabe   m  extinct     45
491       amasa   m  extinct     37
259        maud   m  extinct     31
318         lim   m  extinct     30
114         ham   m  extinct     29
532         nim   m  extinct     28
339        esta   m  extinct     27
659        lish   m  extinct     24
761        doll   m  extinct     24
1028       bose   m  extinct     20
466       rhoda   m  extinct     12
991        lone   m  extinct     11
868        bunk   m  extinct     10
408      schley   m  extinct     10
631         edw   m  extinct      6
979        roll   m  extinct      5

In [86]:
endangered_f_97 = names_sorter("f", f_top_1000_64, 1997, max_data_year)

In [87]:
endangered_m_97 = names_sorter("m", m_top_1000_64, 1997, max_data_year)

In [88]:
pd.set_option('display.max_rows', None)
print(endangered_f_97[endangered_f_97["Rating"] == "vulnerable"].sort_values(by="Count", ascending=False))

            Name Sex      Rating   Count
712        ethel   f  vulnerable  278922
308     gertrude   f  vulnerable  177100
588       bessie   f  vulnerable  170140
502          sue   f  vulnerable  144536
62         wilma   f  vulnerable  140101
790        patsy   f  vulnerable  119448
1374     delores   f  vulnerable  117821
1523      carole   f  vulnerable  110688
136       vickie   f  vulnerable  110046
1080      margie   f  vulnerable  106004
695        velma   f  vulnerable   86752
949       sherri   f  vulnerable   83667
199        mamie   f  vulnerable   77907
1         beulah   f  vulnerable   73252
799      alberta   f  vulnerable   70365
594        verna   f  vulnerable   69113
969        patty   f  vulnerable   62452
146        lynne   f  vulnerable   61957
499        gayle   f  vulnerable   61357
617        sheri   f  vulnerable   60464
780         erma   f  vulnerable   54949
1073      muriel   f  vulnerable   54884
942       sallie   f  vulnerable   49961
1081      nettie   f  vulnerable   49443
1092      shelia   f  vulnerable   47780
1281      doreen   f  vulnerable   46431
976        maude   f  vulnerable   45754
166        freda   f  vulnerable   42527
1402      lorene   f  vulnerable   39379
1476         ora   f  vulnerable   39278
1243        tami   f  vulnerable   37927
1217      bonita   f  vulnerable   37842
1514       cheri   f  vulnerable   36068
1002      tammie   f  vulnerable   35380
1343     sherrie   f  vulnerable   35148
1432      lucile   f  vulnerable   34887
300        ronda   f  vulnerable   34315
80           fay   f  vulnerable   32059
337        myrna   f  vulnerable   31700
314         alta   f  vulnerable   28931
1355       leola   f  vulnerable   28129
267       sondra   f  vulnerable   27074
1015     susanne   f  vulnerable   26094
801       glenna   f  vulnerable   25624
511        trudy   f  vulnerable   25623
1209      frieda   f  vulnerable   25506
65      jeannine   f  vulnerable   24066
555        lorie   f  vulnerable   21964
1234        dale   f  vulnerable   21887
88         marcy   f  vulnerable   21787
1079      elnora   f  vulnerable   21363
15       ladonna   f  vulnerable   21233
816      christi   f  vulnerable   20910
644       cecile   f  vulnerable   20421
1060      robert   f  vulnerable   20119
885       noreen   f  vulnerable   20108
1330      terrie   f  vulnerable   19729
774    claudette   f  vulnerable   18784
1016        lupe   f  vulnerable   18621
170      saundra   f  vulnerable   17851
87        arline   f  vulnerable   17590
318       lorrie   f  vulnerable   17342
1147     loraine   f  vulnerable   17284
365       jeanie   f  vulnerable   17148
1205     nanette   f  vulnerable   16894
891      sharron   f  vulnerable   16856
1126        nona   f  vulnerable   16708
598      roseann   f  vulnerable   15878
892        lelia   f  vulnerable   15645
1302       jerri   f  vulnerable   15506
1227      edwina   f  vulnerable   15465
125     lynnette   f  vulnerable   15226
1524      kathie   f  vulnerable   15086
543     marietta   f  vulnerable   15055
1130      deanne   f  vulnerable   14851
567       jannie   f  vulnerable   14829
492       corine   f  vulnerable   14547
1119       wendi   f  vulnerable   14522
506         nita   f  vulnerable   14268
1019       marci   f  vulnerable   14026
1398      benita   f  vulnerable   13669
1336        kris   f  vulnerable   13571
564       sheree   f  vulnerable   13554
670    georgette   f  vulnerable   13462
11          kaye   f  vulnerable   13204
810    maryellen   f  vulnerable   13144
948      marylou   f  vulnerable   13112
552      lawanda   f  vulnerable   12093
988       coleen   f  vulnerable   11998
436         leta   f  vulnerable   11944
211        twila   f  vulnerable   11922
812        kitty   f  vulnerable   11657
920       cherry   f  vulnerable   11580
910     claudine   f  vulnerable   11323
819         lona   f  vulnerable   10907
1443       gayla   f  vulnerable   10838
1397      freida   f  vulnerable   10794
1029      denice   f  vulnerable   10649
833       alvina   f  vulnerable   10502
115     lucretia   f  vulnerable   10430
198      danette   f  vulnerable   10392
829        merry   f  vulnerable   10369
629         judi   f  vulnerable   10351
229      felecia   f  vulnerable   10268
482        deann   f  vulnerable   10185
442        sandi   f  vulnerable   10101
313        gilda   f  vulnerable   10078
1353     margret   f  vulnerable   10068
1089        ione   f  vulnerable   10004
977      shellie   f  vulnerable    9967
802      latanya   f  vulnerable    9850
246    celestine   f  vulnerable    9809
814      richard   f  vulnerable    9530
840        suzan   f  vulnerable    9081
364        dovie   f  vulnerable    9076
796         elda   f  vulnerable    8970
1335        alva   f  vulnerable    8889
422       roxann   f  vulnerable    8885
468       lolita   f  vulnerable    8664
371       kerrie   f  vulnerable    8589
1489      thomas   f  vulnerable    8511
1531     darleen   f  vulnerable    8332
160    jacquline   f  vulnerable    8029
986       charla   f  vulnerable    8026
201         geri   f  vulnerable    8021
985          ona   f  vulnerable    7939
7         sammie   f  vulnerable    7833
265    antonette   f  vulnerable    7803
1407    cathrine   f  vulnerable    7716
1104       cindi   f  vulnerable    7696
129      valorie   f  vulnerable    7556
497      marilee   f  vulnerable    7434
523     charleen   f  vulnerable    7384
435        candi   f  vulnerable    7356
1305    roseanne   f  vulnerable    7307
94         berta   f  vulnerable    7286
324       dorcas   f  vulnerable    7268
945       carmel   f  vulnerable    7216
82       mariann   f  vulnerable    7192
96         alpha   f  vulnerable    7188
271       maryjo   f  vulnerable    7109
1286     ruthann   f  vulnerable    7098
1401      lonnie   f  vulnerable    6995
1024   carmelita   f  vulnerable    6965
577      socorro   f  vulnerable    6912
345      carleen   f  vulnerable    6744
904       rosita   f  vulnerable    6726
261       mickey   f  vulnerable    6546
1096      janeen   f  vulnerable    6544
1007      terese   f  vulnerable    6503
230      bettina   f  vulnerable    6482
1184     teressa   f  vulnerable    6480
1103    carlotta   f  vulnerable    6462
951        aleta   f  vulnerable    6446
101       sharla   f  vulnerable    6444
1294     laquita   f  vulnerable    6400
1232        juli   f  vulnerable    6351
769     maribeth   f  vulnerable    6098
936        nicki   f  vulnerable    6083
1317       dawna   f  vulnerable    6017
189        lovie   f  vulnerable    5887
542     roseanna   f  vulnerable    5881
753       jonnie   f  vulnerable    5880
921        nelle   f  vulnerable    5794
197        missy   f  vulnerable    5776
620       oralia   f  vulnerable    5758
679     carolann   f  vulnerable    5652
91          fawn   f  vulnerable    5635
909          ray   f  vulnerable    5606
1536      kattie   f  vulnerable    5592
1452      rosina   f  vulnerable    5574
1005    filomena   f  vulnerable    5550
1474        rona   f  vulnerable    5444
5       marcelle   f  vulnerable    5414
1190       kevin   f  vulnerable    5337
1041        cary   f  vulnerable    5323
77     ernestina   f  vulnerable    5309
873        kandy   f  vulnerable    5306
749     charisse   f  vulnerable    5296
610         vina   f  vulnerable    5267
370      jerilyn   f  vulnerable    5251
1063  concepcion   f  vulnerable    5224
1088    jannette   f  vulnerable    5219
736       marvel   f  vulnerable    5198
764      jacalyn   f  vulnerable    5185
807       roxane   f  vulnerable    5179
1522       meryl   f  vulnerable    5167
126       candis   f  vulnerable    5164
1122      marita   f  vulnerable    5088
815       evonne   f  vulnerable    5057
682        vilma   f  vulnerable    4989
1420        dori   f  vulnerable    4952
181       leslee   f  vulnerable    4905
1094        nena   f  vulnerable    4896
726         roni   f  vulnerable    4707
525      erlinda   f  vulnerable    4656
490        alida   f  vulnerable    4650
995    elizebeth   f  vulnerable    4603
1189        vita   f  vulnerable    4591
1340       karri   f  vulnerable    4493
263        sibyl   f  vulnerable    4464
454        daryl   f  vulnerable    4419
439        dedra   f  vulnerable    4418
1148    herlinda   f  vulnerable    4410
580      marylin   f  vulnerable    4379
389        santa   f  vulnerable    4370
1050    trinidad   f  vulnerable    4354
600    jeraldine   f  vulnerable    4345
766        renea   f  vulnerable    4335
1484       marti   f  vulnerable    4321
1519      verona   f  vulnerable    4314
1107    migdalia   f  vulnerable    4298
29       linette   f  vulnerable    4285
574         suzy   f  vulnerable    4270
259         cruz   f  vulnerable    4232
277          eda   f  vulnerable    4208
901       felice   f  vulnerable    4188
595        carma   f  vulnerable    4169
776      karlene   f  vulnerable    4167
1491        inga   f  vulnerable    4127
1226       leesa   f  vulnerable    4124
417       elayne   f  vulnerable    4114
742      delfina   f  vulnerable    4037
465      dominga   f  vulnerable    4034
407        suzie   f  vulnerable    3984
808        lissa   f  vulnerable    3979
803     jacqulyn   f  vulnerable    3958
1212      cammie   f  vulnerable    3946
1236    sherilyn   f  vulnerable    3930
857        liane   f  vulnerable    3879
1461   augustine   f  vulnerable    3842
374        ellyn   f  vulnerable    3836
31       loriann   f  vulnerable    3785
650    thomasina   f  vulnerable    3765
658       lanita   f  vulnerable    3721
1269     annamae   f  vulnerable    3715
1272    vincenza   f  vulnerable    3692
132      elenora   f  vulnerable    3661
1121        viva   f  vulnerable    3605
1495    carolyne   f  vulnerable    3587
1118         ena   f  vulnerable    3587
462        cyndi   f  vulnerable    3568
51        zandra   f  vulnerable    3547
348     domenica   f  vulnerable    3503
1078    kathlene   f  vulnerable    3500
630   sanjuanita   f  vulnerable    3476
932         leda   f  vulnerable    3448
1368       larae   f  vulnerable    3426
994         elba   f  vulnerable    3393
495        lonna   f  vulnerable    3351
319        ilona   f  vulnerable    3332
1416      amparo   f  vulnerable    3316
640       delisa   f  vulnerable    3251
179      matilde   f  vulnerable    3220
674      lorenza   f  vulnerable    3184
586        minna   f  vulnerable    3151
412        shaun   f  vulnerable    3129
1152     santina   f  vulnerable    3102
487      candyce   f  vulnerable    3014
494        signe   f  vulnerable    3003
828         zita   f  vulnerable    2977
789     claribel   f  vulnerable    2977
809        phebe   f  vulnerable    2958
947       venice   f  vulnerable    2946
445       arlena   f  vulnerable    2830
676     antonina   f  vulnerable    2804
1237        arla   f  vulnerable    2789
1404        jack   f  vulnerable    2734
50       melodee   f  vulnerable    2722
896     madelene   f  vulnerable    2704
1276       elvie   f  vulnerable    2704
1025      dennis   f  vulnerable    2692
591     ruthanne   f  vulnerable    2685
196      rosaria   f  vulnerable    2551
550         nana   f  vulnerable    2530
1319      libbie   f  vulnerable    2513
1145      lovina   f  vulnerable    2479
128         jaye   f  vulnerable    2468
56         perri   f  vulnerable    2448
1326       audie   f  vulnerable    2436
1513      madlyn   f  vulnerable    2377
536       vashti   f  vulnerable    2355
804        louie   f  vulnerable    2346
562       dannie   f  vulnerable    2309
1039        zana   f  vulnerable    2288
728        vella   f  vulnerable    2283
671     sanjuana   f  vulnerable    2283
793    augustina   f  vulnerable    2280
528       elenor   f  vulnerable    2268
43        stasia   f  vulnerable    2259
1210       jetta   f  vulnerable    2254
74        ailene   f  vulnerable    2197
1539       lelah   f  vulnerable    2187
500        irena   f  vulnerable    2186
946        dayle   f  vulnerable    2181
609       eudora   f  vulnerable    2179
1393         leo   f  vulnerable    2136
163       joline   f  vulnerable    2136
800    katharina   f  vulnerable    2121
279       leisha   f  vulnerable    2108
916         lady   f  vulnerable    2068
384        tilda   f  vulnerable    2040
1515      verena   f  vulnerable    1989
1391       oliva   f  vulnerable    1976
732       gracia   f  vulnerable    1952
1315   hildegard   f  vulnerable    1945
1127  clarabelle   f  vulnerable    1945
1439       allyn   f  vulnerable    1915
1046      flavia   f  vulnerable    1843
393        dessa   f  vulnerable    1817
60       elenore   f  vulnerable    1806
296         tula   f  vulnerable    1805
1128        illa   f  vulnerable    1800
1240    mathilde   f  vulnerable    1793
100       honora   f  vulnerable    1721
847      marinda   f  vulnerable    1714
1070     evaline   f  vulnerable    1708
557    theodosia   f  vulnerable    1705
1296      sarrah   f  vulnerable    1636
238     katharyn   f  vulnerable    1614
1280       nelia   f  vulnerable    1580
760        sadye   f  vulnerable    1532
709       azalee   f  vulnerable    1526
424         adel   f  vulnerable    1494
1250       lilie   f  vulnerable    1473
781     celestia   f  vulnerable    1414
1067   rosabelle   f  vulnerable    1379
112      evalena   f  vulnerable    1378
305         aili   f  vulnerable    1376
987         alys   f  vulnerable    1359
1101        zeta   f  vulnerable    1354
83         carra   f  vulnerable    1353
1136        sada   f  vulnerable    1308
46          bina   f  vulnerable    1288
4          rosey   f  vulnerable    1288
1473        vira   f  vulnerable    1274
848       deliah   f  vulnerable    1260
1307       donia   f  vulnerable    1219
886         alla   f  vulnerable    1192
431       daisie   f  vulnerable    1178
1090       zelia   f  vulnerable    1177
233       pheobe   f  vulnerable    1136
1348    eleonore   f  vulnerable    1088
1532        vela   f  vulnerable    1082
983      forrest   f  vulnerable    1058
385          ama   f  vulnerable    1050
515    tennessee   f  vulnerable     986
1170        mora   f  vulnerable     945
86       hazelle   f  vulnerable     932
1262        ebba   f  vulnerable     925
461        olena   f  vulnerable     920
9          arley   f  vulnerable     898
572        leala   f  vulnerable     875
75         lovey   f  vulnerable     859
1388        elza   f  vulnerable     831
813         nira   f  vulnerable     804
956      marilla   f  vulnerable     802
641         mame   f  vulnerable     672
285       noemie   f  vulnerable     666
872      arietta   f  vulnerable     633
1191      byrdie   f  vulnerable     621
1027         zoa   f  vulnerable     616
1278      forest   f  vulnerable     593
1545      pearla   f  vulnerable     559
990       leland   f  vulnerable     557
830          iza   f  vulnerable     474

In [89]:
pd.set_option('display.max_rows', None)
print(endangered_m_97[endangered_m_97["Rating"] == "vulnerable"].sort_values(by="Count", ascending=False))

             Name Sex      Rating  Count
1213          bob   m  vulnerable  92986
67          homer   m  vulnerable  60912
1240       wilbur   m  vulnerable  56906
1314         lynn   m  vulnerable  52391
59        delbert   m  vulnerable  46930
877         gregg   m  vulnerable  36512
365         rufus   m  vulnerable  36074
614       carroll   m  vulnerable  35431
93            kim   m  vulnerable  34951
1232        dewey   m  vulnerable  34373
69           bert   m  vulnerable  33585
1024       elbert   m  vulnerable  33511
1264       billie   m  vulnerable  31637
367         merle   m  vulnerable  30666
875         doyle   m  vulnerable  30400
1262       grover   m  vulnerable  27113
88             ed   m  vulnerable  26205
663       garland   m  vulnerable  23857
1027       burton   m  vulnerable  22486
1283       rodger   m  vulnerable  21556
1078       johnie   m  vulnerable  20930
11         sammie   m  vulnerable  20836
903          phil   m  vulnerable  20036
1324       adolph   m  vulnerable  18745
439        bobbie   m  vulnerable  18422
1229          ned   m  vulnerable  17292
334           hal   m  vulnerable  16784
1222         curt   m  vulnerable  16680
651        russel   m  vulnerable  16610
594        norris   m  vulnerable  16456
1018      thurman   m  vulnerable  16392
1166        irwin   m  vulnerable  15946
572          mary   m  vulnerable  15173
1398      maynard   m  vulnerable  14918
751         odell   m  vulnerable  14883
33       frederic   m  vulnerable  14440
714        weldon   m  vulnerable  14249
476        delmar   m  vulnerable  14242
458          scot   m  vulnerable  13721
923       linwood   m  vulnerable  12776
1164         cleo   m  vulnerable  11527
1243      freeman   m  vulnerable  10991
1121         dirk   m  vulnerable  10955
891      herschel   m  vulnerable  10674
147         sandy   m  vulnerable  10458
344        lavern   m  vulnerable  10236
3        pasquale   m  vulnerable  10138
173        lenard   m  vulnerable   9997
1308      rolland   m  vulnerable   9868
895         garth   m  vulnerable   9666
43          cliff   m  vulnerable   9307
1399       bernie   m  vulnerable   9225
551        dannie   m  vulnerable   9137
1311    ferdinand   m  vulnerable   8909
959           rod   m  vulnerable   8744
1104       tracey   m  vulnerable   8688
229        wilton   m  vulnerable   8653
1351        ivory   m  vulnerable   8568
409       jerrold   m  vulnerable   8467
1318      fredric   m  vulnerable   8395
1134         odis   m  vulnerable   8229
1349         thad   m  vulnerable   8219
1042       newton   m  vulnerable   8177
779        buster   m  vulnerable   8173
98           mose   m  vulnerable   7935
767      napoleon   m  vulnerable   7805
500       lindsey   m  vulnerable   7735
529      stanford   m  vulnerable   7727
23          elroy   m  vulnerable   7476
1362        nicky   m  vulnerable   7475
322        jerold   m  vulnerable   7434
345          huey   m  vulnerable   7098
1147        rubin   m  vulnerable   7054
1342          tad   m  vulnerable   6929
819        hilton   m  vulnerable   6925
166         jamey   m  vulnerable   6755
217       stanton   m  vulnerable   6738
336         arlie   m  vulnerable   6712
1070       harmon   m  vulnerable   6607
560        felton   m  vulnerable   6588
307         toney   m  vulnerable   6416
1335       kelley   m  vulnerable   6286
521           art   m  vulnerable   6141
1185         russ   m  vulnerable   6131
1117      whitney   m  vulnerable   5994
839        antone   m  vulnerable   5967
1313        kraig   m  vulnerable   5951
1029        elden   m  vulnerable   5921
448        lauren   m  vulnerable   5818
177        rollin   m  vulnerable   5771
608      aloysius   m  vulnerable   5724
542           val   m  vulnerable   5657
526       rosario   m  vulnerable   5611
373        rupert   m  vulnerable   5595
863         artis   m  vulnerable   5377
1192    margarito   m  vulnerable   4887
1339        santo   m  vulnerable   4876
1190    lafayette   m  vulnerable   4861
222        lesley   m  vulnerable   4797
36         enrico   m  vulnerable   4767
238        delton   m  vulnerable   4751
746         giles   m  vulnerable   4732
1162        britt   m  vulnerable   4710
1025      glendon   m  vulnerable   4695
1103   christophe   m  vulnerable   4476
762          oran   m  vulnerable   4447
451         albin   m  vulnerable   4431
1352         rich   m  vulnerable   4407
531        leeroy   m  vulnerable   4404
358       terrill   m  vulnerable   4365
568       farrell   m  vulnerable   4355
596      benjiman   m  vulnerable   4307
641      richmond   m  vulnerable   4305
915         lorne   m  vulnerable   4302
846       rowland   m  vulnerable   4279
622         maria   m  vulnerable   4278
702   bartholomew   m  vulnerable   4271
1326       gustav   m  vulnerable   4267
870        adrain   m  vulnerable   4252
1247         obie   m  vulnerable   4165
785       ritchie   m  vulnerable   4120
235       willian   m  vulnerable   4074
57         gaston   m  vulnerable   4053
674          enos   m  vulnerable   3991
40        refugio   m  vulnerable   3984
865        christ   m  vulnerable   3977
1319     jefferey   m  vulnerable   3973
1270        lonzo   m  vulnerable   3961
51          elgin   m  vulnerable   3959
569      reinaldo   m  vulnerable   3941
443      prentice   m  vulnerable   3929
75        gaetano   m  vulnerable   3861
805       carlyle   m  vulnerable   3856
653        vinson   m  vulnerable   3841
480          nels   m  vulnerable   3841
945       allison   m  vulnerable   3825
955        denzil   m  vulnerable   3775
983       sherwin   m  vulnerable   3769
538       tillman   m  vulnerable   3732
1095       darvin   m  vulnerable   3708
601           mel   m  vulnerable   3693
773           sal   m  vulnerable   3663
917        randel   m  vulnerable   3651
808         jerel   m  vulnerable   3612
1305        brien   m  vulnerable   3588
189      charlton   m  vulnerable   3530
434      porfirio   m  vulnerable   3526
265      thurston   m  vulnerable   3501
164          chip   m  vulnerable   3493
739         kevan   m  vulnerable   3479
1067          ivy   m  vulnerable   3460
559       isidore   m  vulnerable   3421
634        lovell   m  vulnerable   3412
800         brook   m  vulnerable   3391
31          davey   m  vulnerable   3346
858       michale   m  vulnerable   3274
1125        urban   m  vulnerable   3264
576         elwyn   m  vulnerable   3231
1108         chas   m  vulnerable   3213
632         ennis   m  vulnerable   3204
1291       donato   m  vulnerable   3126
737    florentino   m  vulnerable   3105
12         clovis   m  vulnerable   3092
435        stoney   m  vulnerable   3092
260     florencio   m  vulnerable   3090
326          nils   m  vulnerable   3083
977       eusebio   m  vulnerable   3077
1332      raynard   m  vulnerable   3061
1005        oneal   m  vulnerable   3049
585       pernell   m  vulnerable   3037
741          cris   m  vulnerable   3033
686       gardner   m  vulnerable   3016
1039          sid   m  vulnerable   3007
176         rance   m  vulnerable   3002
284        silvio   m  vulnerable   3000
958        farris   m  vulnerable   2991
655          rand   m  vulnerable   2960
510          blas   m  vulnerable   2921
160       americo   m  vulnerable   2911
1287        hazel   m  vulnerable   2889
611    wellington   m  vulnerable   2879
1155      renaldo   m  vulnerable   2879
157        gerrit   m  vulnerable   2877
929         franz   m  vulnerable   2864
1207       lawton   m  vulnerable   2861
790      stafford   m  vulnerable   2850
650       terance   m  vulnerable   2840
961         brion   m  vulnerable   2807
766         darcy   m  vulnerable   2785
1233     sheridan   m  vulnerable   2768
964          anna   m  vulnerable   2756
393           zeb   m  vulnerable   2750
925          olan   m  vulnerable   2732
1109       huston   m  vulnerable   2714
489       parrish   m  vulnerable   2706
39         renard   m  vulnerable   2690
985          davy   m  vulnerable   2682
78           rock   m  vulnerable   2681
1101     shedrick   m  vulnerable   2675
1221      rexford   m  vulnerable   2648
403    washington   m  vulnerable   2644
472     celestino   m  vulnerable   2638
826          walt   m  vulnerable   2634
1406          joy   m  vulnerable   2630
786         gorge   m  vulnerable   2609
628         micky   m  vulnerable   2584
456        hurley   m  vulnerable   2581
1021         arch   m  vulnerable   2572
911        pascal   m  vulnerable   2550
1331      gennaro   m  vulnerable   2542
696          olaf   m  vulnerable   2531
240         maury   m  vulnerable   2512
701        kenney   m  vulnerable   2500
488        kerwin   m  vulnerable   2470
1172         jens   m  vulnerable   2456
255        jerrel   m  vulnerable   2448
83         sumner   m  vulnerable   2444
1409      corbett   m  vulnerable   2433
784         yancy   m  vulnerable   2433
588       danniel   m  vulnerable   2418
482       sanders   m  vulnerable   2392
1051       mikeal   m  vulnerable   2386
268          desi   m  vulnerable   2347
125     anastacio   m  vulnerable   2316
706         ricki   m  vulnerable   2303
49        talmage   m  vulnerable   2281
108        garner   m  vulnerable   2279
1004        young   m  vulnerable   2234
384      fidencio   m  vulnerable   2232
730         worth   m  vulnerable   2204
477       berkley   m  vulnerable   2202
1353      zebulon   m  vulnerable   2149
721           ole   m  vulnerable   2125
158           tex   m  vulnerable   2120
426      dionicio   m  vulnerable   2094
453       candido   m  vulnerable   2087
423        fenton   m  vulnerable   2046
275         coley   m  vulnerable   2029
682       kimball   m  vulnerable   2008
123         eston   m  vulnerable   2006
713         arlis   m  vulnerable   1972
997        vergil   m  vulnerable   1968
850       wheeler   m  vulnerable   1916
1118     carlisle   m  vulnerable   1862
675          cass   m  vulnerable   1860
135       manning   m  vulnerable   1840
127       wilhelm   m  vulnerable   1828
377     katherine   m  vulnerable   1824
660       julious   m  vulnerable   1756
861        lorenz   m  vulnerable   1754
769       osborne   m  vulnerable   1754
1226        julia   m  vulnerable   1743
617          arno   m  vulnerable   1723
1359       gaines   m  vulnerable   1717
1096        orlin   m  vulnerable   1683
797       soloman   m  vulnerable   1679
355      reynolds   m  vulnerable   1674
321          webb   m  vulnerable   1658
788         ashby   m  vulnerable   1655
183       georgie   m  vulnerable   1645
795        jessee   m  vulnerable   1645
768          avon   m  vulnerable   1641
1047       wright   m  vulnerable   1639
499        berlin   m  vulnerable   1635
112       hartley   m  vulnerable   1608
0       arlington   m  vulnerable   1586
523       hiroshi   m  vulnerable   1565
1100        einar   m  vulnerable   1563
1188     griffith   m  vulnerable   1550
948          taft   m  vulnerable   1544
573         ronal   m  vulnerable   1541
731        destry   m  vulnerable   1502
666       horatio   m  vulnerable   1443
1375      lillian   m  vulnerable   1429
460    victoriano   m  vulnerable   1415
636         grace   m  vulnerable   1405
683           doc   m  vulnerable   1391
760        tilden   m  vulnerable   1345
97           eber   m  vulnerable   1328
820          jobe   m  vulnerable   1325
18          champ   m  vulnerable   1289
1063         hale   m  vulnerable   1282
842           tal   m  vulnerable   1265
197       chauncy   m  vulnerable   1257
351         elihu   m  vulnerable   1236
1300        adams   m  vulnerable   1230
328       chancey   m  vulnerable   1228
517         aleck   m  vulnerable   1223
249         shade   m  vulnerable   1156
506       grafton   m  vulnerable   1080
396          myer   m  vulnerable   1073
167        harman   m  vulnerable   1049
27         colvin   m  vulnerable   1040
86           love   m  vulnerable    988
188          amil   m  vulnerable    982
615         mills   m  vulnerable    919
133        hughes   m  vulnerable    919
320          ella   m  vulnerable    901
976        sigurd   m  vulnerable    869
193       redmond   m  vulnerable    819
280        harden   m  vulnerable    771
996          hays   m  vulnerable    740
1201      prosper   m  vulnerable    678
190          cato   m  vulnerable    675
1273        adlai   m  vulnerable    608
427        silver   m  vulnerable    528
466        alanzo   m  vulnerable    494
834         pryor   m  vulnerable    484
172       auguste   m  vulnerable    468
64        captain   m  vulnerable    466
1074       ephram   m  vulnerable    453
1202        essex   m  vulnerable    435
1358           ab   m  vulnerable    380
942         emett   m  vulnerable    351
1259        north   m  vulnerable    333
48         reason   m  vulnerable    255
1            shep   m  vulnerable    235