# Side Projects
Short data projects so data notebook doesn't get crowded

In [1]:
# Imports and colors and numbers that won't change
import pandas as pd
import matplotlib.pyplot as plt
import random
import numpy as np
import seaborn as sns
import scipy.stats as stats
#First year of data will not change, last year is not inclusive
min_data_year = 1880
max_data_year = 2026
female_color = 'xkcd:pink'
male_color = 'xkcd:light blue'
default_color = 'xkcd:periwinkle'
default_color2 = 'xkcd:grass green'
colors = ['xkcd:red','xkcd:orange','xkcd:mustard','xkcd:grass green', 'xkcd:light blue','xkcd:cerulean','xkcd:indigo', 
          'xkcd:lavender', 'xkcd:pink', 'xkcd:black', 'xkcd:tan', 'xkcd:grey blue']
generation_starts = {'Missionary' : (1880, 1883), 'Lost' : (1883, 1901), 'Greatest' : (1901, 1928), 'Silent' : (1928, 1946), 'Boomers' : (1946,1965), 'Gen X' : (1965,1981), 'Milennial' : (1981,1997),
                     'Gen X' : (1997,2010), 'Gen Alpha' : (2010,2025), 'Gen Beta' : (2025,2040)}

In [2]:
import functions as fun
fun.init(min_data_year, max_data_year, "names")

In [ ]:
# number of babies in beyond top 1000 dataset
num_in_year = []
for i in range(min_data_year, max_data_year):
    f = fun.get_year_list_one("f", i)
    m = fun.get_year_list_one("m", i)
    num_in_year.append(f["Count"].sum() + m["Count"].sum())
for n in num_in_year:
    print(n)

201484
192688
221533
216945
243460
240854
255316
247391
299474
288946
301401
286673
334374
325223
338690
351020
357483
346957
381454
339233
450258
345812
386733
381200
403484
423923
428451
465390
488648
511224
590711
644279
988061
1137112
1416343
1832427
1934414
2006749
2171111
2110239
2262645
2334507
2289157
2302468
2381614
2333303
2295906
2319346
2260931
2192176
2223305
2104393
2111305
1999456
2076821
2089928
2077595
2130692
2212603
2203464
2302700
2436437
2731880
2822590
2690098
2652945
3195328
3602365
3452526
3484816
3503316
3683696
3797968
3853600
3980666
4015166
4123005
4202087
4134028
4157980
4154261
4142690
4035375
3958585
3887553
3625307
3475638
3394836
3378363
3475190
3606373
3432270
3142852
3016785
3039868
3019218
3034106
3176366
3173696
3326804
3444258
3459237
3507772
3463173
3488665
3569038
3557062
3605616
3695137
3844480
3952585
3895335
3841340
3770400
3717784
3662249
3647307
3625850
3678315
3693973
3780037
3743505
3738396
3802494
3821229
3845147
3956482
3998031
3931088
3820687
3696271
3658318
3657999
3646327
3707226
3701841
3669760
3577417
3517232
3472582
3342625
3390343
3386139
3315158
3343078
3315343

## Babies Named After Wisconsin Cities

In [ ]:
wi_cities_pop = {"Milwaukee": 563531, "Madison": 285300, "GreenBay": 106311, "Kenosha": 99578, "Racine": 78057, "Appleton": 75344, "EauClaire": 72331, "Waukesha": 71461, "Oshkosh": 67242, "Janesville": 66428, "Allis": 59784, "La Crosse": 51049, "Sheboygan": 49624, "Wauwatosa": 48794, "FondduLac": 44469, "Brookfield": 41268, "MenomoneeFalls": 40700, "Berlin": 40302, "Wausau": 40262, "SunPrairie": 39253, "OakCreek": 38373, "Greenfield": 37232, "Beloit": 36633, "Franklin": 36591, "Manitowoc": 34616, "Fitchburg": 34357, "Bend": 32149, "Mount Pleasant": 28184, "Neenah": 27502, "Superior": 26620, "StevensPoint": 26465, "Muskego": 25759, "DePere": 25453, "Mequon": 25329, "Caledonia": 25240, "Watertown": 22617, "Middleton": 22566, "Howard": 21961, "PleasantPrairie": 21802, "Germantown": 21032, "Oconomowoc": 20002}
# above removed directional words and 'new' and 'city' if it was a separate word 'waukesha city' -> 'waukesha'
# also removed South Milwaukee at 20,233
# removed spaces
wi_f = []
wi_m = []
wi_cities = list(wi_cities_pop.keys())
for n in wi_cities:
    name_counts_f = fun.name_counts_years(n.lower(), 'f', min_data_year, max_data_year)[0]
    name_counts_m = fun.name_counts_years(n.lower(), 'm', min_data_year, max_data_year)[0]
    wi_f.append(sum(name_counts_f))
    wi_m.append(sum(name_counts_m))
wi_f = np.array(wi_f, dtype=int)
wi_m = np.array(wi_m, dtype=int)
x = np.arange(len(wi_cities))
fig, ax = plt.subplots(figsize=(14,8))
plt.bar(x, wi_f, color = female_color, label = 'female')
plt.bar(x, wi_m, bottom=wi_f, color = male_color, label = 'male')
plt.xticks(x, wi_cities, rotation = 90)
plt.legend()
plt.xlabel("city")
plt.ylabel("total count (1880-2024)")
plt.title("Number of babies named after Wisconsin cities (> 20,000 pop.)")
plt.ylim(0, 550000)
for i, (f, m) in enumerate(zip(wi_f, wi_m)):
    if f + m > 0:
        label = f"{f} f; {m} m"
        ax.text(i, f + m + 10, str(label), ha='center', va='bottom', fontsize=8, rotation=90)

## Where On a Map Can You Name Your Kid After?

In [ ]:
geo_features = ["coast", "lake", "lakelyn", "lakelynn", "ocean", "river", "brook", "brooke",
                "brooks", "isla", "islay", "rio", "valley", "bay", "delta", "cove", "loch",
                "marsh", "marsha", "sea", "tide", "bayou", "fjord", "mesa", "sierra", "ridge",
                "hill", "knoll", "canyon", "gorge", "ravine", "basin", "cape", "reef", "prairie",
                "savanna", "savannah", "tundra", "glacier", "dune", "meadow", "woods", "forrest",
                "forest", "island", "terra", "beach", "channel", "cliff", "shoal", "rock", "rocky",
                "stone", "crag", "bar", "gorge", "levee", "vale", "alpine", "oasis", "summit",
                "dale", "dell", "glen", "glenn", "glenna", "terrace", "taiga"]
# directions, "new", variations of Guinea, ands separated, saint removed, islands, sierra, united, emirates, san
countries = ["Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua", "Barbuda", 
             "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", 
             "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan",
             "Bolivia", "Bosnia", "Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", 
             "BurkinaFaso", "Burundi", "CaboVerde", "Cambodia", "Cameroon", "Canada", 
             "CentralAfricanRepublic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo", 
             "CostaRica", "Croatia", "Cuba", "Cyprus", "Czechia", "Denmark", "Djibouti", 
             "Dominica", "Ecuador", "Egypt", "Salvador", "Guinea", "Eritrea", 
             "Estonia", "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", 
             "Georgia", "Germany", "Ghana", "Greece", "Greenland", "Grenada", "Guatemala", "Guinea", 
             "Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India",
             "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Ivory", "Jamaica", "Japan", 
             "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos",
             "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", 
             "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", 
             "Marshall", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova",
             "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", 
             "Nauru", "Nepal", "Netherlands", "Holland", "Zealand", "Nicaragua", "Niger", "Nigeria", "Korea",
             "Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama", 
             "Papua", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", 
             "Romania", "Russia", "Rwanda", "Kitts", "Nevis", "Lucia", "Vincent", 
             "Grenadines", "Samoa", "Marino", "SaoTome", "Scotland", "Principe", "SaudiArabia", "Senegal", 
             "Serbia", "Seychelles", "Leone", "Singapore", "Slovakia", "Slovenia", 
             "Solomon", "Somalia", "Spain", "SriLanka", "Sudan", "Suriname",
             "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", 
             "TimorLeste", "Togo", "Tonga", "Trinidad", "Tobago", "Tunisia", "Turkey", 
             "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "Arab", "Kingdom", "Britain", "England",
             "States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican", "Venezuela", "Vietnam", 
             "Wales", "Yemen", "Zambia", "Zimbabwe", "Kosovo", "Sahara"]
continent = ["america", "europe", "asia", "africa", "antarctica"]
almost_countries = ["icelyn", "icelynn", "scotlyn", "scotlynn", "irelyn", "irelynn", "thailyn", "thailynn"]
directions = ["north", "east", "south", "west"]
world_cities = ["York", "Angeles", "Chicago", "Houston", "Toronto", "Miami", "Francisco", 
                "Seattle", "Boston", "Atlanta", "Dallas", "Montreal", "Vancouver", "Vegas", 
                "Denver", "Phoenix", "Minneapolis", "Detroit", "Havana", "Panama", "Bogota", 
                "Lima", "Santiago", "Caracas", "London", "Paris", "Berlin", "Madrid", "Rome",
                "Amsterdam", "Barcelona", "Vienna", "Prague", "Warsaw", "Budapest", "Stockholm", 
                "Copenhagen", "Helsinki", "Oslo", "Zurich", "Geneva", "Brussels", "Lisbon", 
                "Athens", "Munich", "Hamburg", "Frankfurt", "Milan", "Naples", "Venice", "Florence", 
                "Edinburgh", "Dublin", "Reykjavik", "Kyiv", "Moscow", "Istanbul", "Ankara", 
                "Sofia", "Sarajevo", "Riga", "Tallinn", "Vilnius", "Minsk", "Yerevan", "Tirana", 
                "Luxembourg", "Dubai", "Riyadh", "Jeddah", "Doha", "Beirut", "Damascus", 
                "Baghdad", "Tehran", "Amman", "Jerusalem", "Muscat", "Sanaa",
                "Cairo", "Lagos", "Nairobi", "Casablanca", "Accra", "Kinshasa", "Algiers",
                "Mumbai", "Delhi", "Karachi", "Colombo", "Tokyo", "Beijing", "Shanghai", "Seoul", 
                "HongKong", "Taipei", "Osaka", "Kyoto", "Wuhan", "Singapore", "Bangkok", "Manila", 
                "Hanoi", "Vientiane", "Bali", "Sydney", "Melbourne", "Brisbane", "Perth", "Auckland",
                "Wellington", "Adelaide", "Monaco"]
planets = ["mercury", "venus", "earth", "mars", "jupiter", "saturn", "uranus", "neptune", "pluto", "moon", "luna"]
named_features = ["everest", "yosemite", "mckinley", "denali", "rainier", "etna", "vesuvius"]
# find average year of each name? and strength so know if its just scattered
# like if a name had a few blips old but is common now then average should be closer to now
# include mountains like everest?
lists = {"geo": geo_features, "country": countries, "continent": continent, 
         "almost_country": almost_countries, "direction": directions, "city": world_cities, 
         "planet": planets, "named_feature": named_features}

In [ ]:
def calculate_spread(name):
    """Takes in name, finds counts by year for each sex
    returns percent difference, number of years with any data, male and female counts,
    and a metric of when the data is centered"""
    # do name counts years
    f_counts, _ = fun.name_counts_years(name, "f", min_y=min_data_year, max_y=max_data_year)
    m_counts, _ = fun.name_counts_years(name, "m", min_y=min_data_year, max_y=max_data_year)
    # do percent difference
    num_f = sum(f_counts)
    num_m = sum(m_counts)
    per_diff = fun.calculate_percent_diff(num_f, num_m)
    # add lists together
    counts = [f_counts[i] + m_counts[i] for i in range(len(f_counts))]
    # find center of data by finding year where sum surpasses current halfway point
    years = sum(1 for i in counts if i != 0)
    half_count = sum(counts) / 2
    s = 0
    center = -1
    for i in range(len(counts)):
        s += counts[i]
        if s >= half_count:
            center = i + min_data_year
            break
    return center, years, per_diff, num_f, num_m

In [ ]:
# iterate over all names
geo_names = pd.DataFrame(columns = ["name", "type", "count", "f_count", "m_count", 
                                    "per_diff", "center_year", "years"])
# make dataframe of values with column for type of name (country, feature)
for l in lists.keys():
    for n in lists[l]:
        center, years, per_diff, num_f, num_m = calculate_spread(n.lower())
        geo_names.loc[len(geo_names)] = [n, l, num_f + num_m, num_f, num_m, 
                                          per_diff, center, years]

In [ ]:
pd.set_option('display.max_rows', None)
geo_names[geo_names["type"] == "country"]

,name,type,count,f_count,m_count,per_diff,center_year,years
68,Afghanistan,country,0,0,0,200.000000,1880,0
69,Albania,country,0,0,0,200.000000,1880,0
70,Algeria,country,32,32,0,200.000000,1994,6
71,Andorra,country,0,0,0,200.000000,1880,0
72,Angola,country,0,0,0,200.000000,1880,0
73,Antigua,country,0,0,0,200.000000,1880,0
74,Barbuda,country,0,0,0,200.000000,1880,0
75,Argentina,country,442,442,0,200.000000,1963,65
76,Armenia,country,163,163,0,200.000000,1921,23
77,Australia,country,350,339,11,187.428571,1932,47
78,Austria,country,17,17,0,200.000000,1992,3
79,Azerbaijan,country,0,0,0,200.000000,1880,0
80,Bahamas,country,0,0,0,200.000000,1880,0
81,Bahrain,country,0,0,0,200.000000,1880,0
82,Bangladesh,country,0,0,0,200.000000,1880,0
83,Barbados,country,0,0,0,200.000000,1880,0
84,Belarus,country,0,0,0,200.000000,1880,0
85,Belgium,country,0,0,0,200.000000,1880,0
86,Belize,country,85,85,0,200.000000,2018,13
87,Benin,country,0,0,0,200.000000,1880,0
88,Bhutan,country,0,0,0,200.000000,1880,0
89,Bolivia,country,5,5,0,200.000000,1990,1
90,Bosnia,country,0,0,0,200.000000,1880,0
91,Herzegovina,country,0,0,0,200.000000,1880,0
92,Botswana,country,0,0,0,200.000000,1880,0
93,Brazil,country,722,653,69,161.772853,2014,32
94,Brunei,country,0,0,0,200.000000,1880,0
95,Bulgaria,country,0,0,0,200.000000,1880,0
96,BurkinaFaso,country,0,0,0,200.000000,1880,0
97,Burundi,country,0,0,0,200.000000,1880,0
98,CaboVerde,country,0,0,0,200.000000,1880,0
99,Cambodia,country,0,0,0,200.000000,1880,0
100,Cameroon,country,0,0,0,200.000000,1880,0
101,Canada,country,54,54,0,200.000000,1995,10
102,CentralAfricanRepublic,country,0,0,0,200.000000,1880,0
103,Chad,country,241767,1039,240728,198.280990,1978,111
104,Chile,country,0,0,0,200.000000,1880,0
105,China,country,4618,4608,10,199.133824,1993,118
106,Colombia,country,0,0,0,200.000000,1880,0
107,Comoros,country,0,0,0,200.000000,1880,0
108,Congo,country,0,0,0,200.000000,1880,0
109,CostaRica,country,0,0,0,200.000000,1880,0
110,Croatia,country,0,0,0,200.000000,1880,0
111,Cuba,country,616,569,47,169.480519,1922,58
112,Cyprus,country,302,21,281,172.185430,2019,21
113,Czechia,country,0,0,0,200.000000,1880,0
114,Denmark,country,5,0,5,200.000000,1970,1
115,Djibouti,country,0,0,0,200.000000,1880,0
116,Dominica,country,2338,2338,0,200.000000,1982,110
117,Ecuador,country,0,0,0,200.000000,1880,0
118,Egypt,country,5546,4726,820,140.858276,2017,42
119,Salvador,country,49788,183,49605,198.529766,1987,130
120,Guinea,country,0,0,0,200.000000,1880,0
121,Eritrea,country,11,11,0,200.000000,2021,2
122,Estonia,country,0,0,0,200.000000,1880,0
123,Eswatini,country,0,0,0,200.000000,1880,0
124,Ethiopia,country,6,6,0,200.000000,2022,1
125,Fiji,country,0,0,0,200.000000,1880,0
126,Finland,country,12,0,12,200.000000,2021,2
127,France,country,1538,1159,379,101.430429,1939,88
128,Gabon,country,0,0,0,200.000000,1880,0
129,Gambia,country,0,0,0,200.000000,1880,0
130,Georgia,country,167019,166290,729,198.254091,1943,146
131,Germany,country,723,517,206,86.030429,2012,41
132,Ghana,country,12,12,0,200.000000,1969,2
133,Greece,country,0,0,0,200.000000,1880,0
134,Greenland,country,0,0,0,200.000000,1880,0
135,Grenada,country,0,0,0,200.000000,1880,0
136,Guatemala,country,0,0,0,200.000000,1880,0
137,Guinea,country,0,0,0,200.000000,1880,0
138,Bissau,country,0,0,0,200.000000,1880,0
139,Guyana,country,0,0,0,200.000000,1880,0
140,Haiti,country,50,50,0,200.000000,2018,8
141,Honduras,country,0,0,0,200.000000,1880,0
142,Hungary,country,0,0,0,200.000000,1880,0
143,Iceland,country,109,98,11,159.633028,2023,9
144,India,country,24017,23990,27,199.550319,1997,146
145,Indonesia,country,83,83,0,200.000000,1997,10
146,Iran,country,1775,416,1359,106.253521,1993,84
147,Iraq,country,0,0,0,200.000000,1880,0
148,Ireland,country,6556,6347,209,187.248322,2009,51
149,Israel,country,72874,1637,71237,191.014628,2003,146
150,Italy,country,2230,2220,10,198.206278,2016,40
151,Ivory,country,23114,14546,8568,51.726227,1987,145
152,Jamaica,country,1569,1532,37,190.567240,1992,53
153,Japan,country,0,0,0,200.000000,1880,0
154,Jordan,country,536795,135599,401196,98.956585,1998,145
155,Kazakhstan,country,0,0,0,200.000000,1880,0
156,Kenya,country,27553,25412,2141,168.918085,1993,73
157,Kiribati,country,0,0,0,200.000000,1880,0
158,Kuwait,country,0,0,0,200.000000,1880,0
159,Kyrgyzstan,country,0,0,0,200.000000,1880,0
160,Laos,country,0,0,0,200.000000,1880,0
161,Latvia,country,0,0,0,200.000000,1880,0
162,Lebanon,country,0,0,0,200.000000,1880,0
163,Lesotho,country,0,0,0,200.000000,1880,0
164,Liberia,country,0,0,0,200.000000,1880,0
165,Libya,country,14,14,0,200.000000,2011,2
166,Liechtenstein,country,0,0,0,200.000000,1880,0
167,Lithuania,country,0,0,0,200.000000,1880,0
168,Luxembourg,country,0,0,0,200.000000,1880,0
169,Madagascar,country,0,0,0,200.000000,1880,0
170,Malawi,country,0,0,0,200.000000,1880,0
171,Malaysia,country,11031,11031,0,200.000000,2015,39
172,Maldives,country,0,0,0,200.000000,1880,0
173,Mali,country,1495,1406,89,176.187291,2011,52
174,Malta,country,55,55,0,200.000000,1920,9
175,Marshall,country,98604,1157,97447,195.306478,1964,146
176,Mauritania,country,0,0,0,200.000000,1880,0
177,Mauritius,country,0,0,0,200.000000,1880,0
178,Mexico,country,0,0,0,200.000000,1880,0
179,Micronesia,country,0,0,0,200.000000,1880,0
180,Moldova,country,0,0,0,200.000000,1880,0
181,Monaco,country,82,33,49,39.024390,2024,4
182,Mongolia,country,0,0,0,200.000000,1880,0
183,Montenegro,country,0,0,0,200.000000,1880,0
184,Morocco,country,165,6,159,185.454545,2020,14
185,Mozambique,country,0,0,0,200.000000,1880,0
186,Myanmar,country,0,0,0,200.000000,1880,0
187,Namibia,country,0,0,0,200.000000,1880,0
188,Nauru,country,0,0,0,200.000000,1880,0
189,Nepal,country,0,0,0,200.000000,1880,0
190,Netherlands,country,0,0,0,200.000000,1880,0
191,Holland,country,11007,7835,3172,84.727900,2015,124
192,Zealand,country,997,72,925,171.113340,2021,24
193,Nicaragua,country,0,0,0,200.000000,1880,0
194,Niger,country,36,25,11,77.777778,1977,5
195,Nigeria,country,810,810,0,200.000000,1999,46
196,Korea,country,298,298,0,200.000000,2006,34
197,Macedonia,country,0,0,0,200.000000,1880,0
198,Norway,country,0,0,0,200.000000,1880,0
199,Oman,country,45,0,45,200.000000,1973,8
200,Pakistan,country,0,0,0,200.000000,1880,0
201,Palau,country,0,0,0,200.000000,1880,0
202,Palestine,country,169,169,0,200.000000,1931,25
203,Panama,country,0,0,0,200.000000,1880,0
204,Papua,country,0,0,0,200.000000,1880,0
205,Paraguay,country,0,0,0,200.000000,1880,0
206,Peru,country,5,5,0,200.000000,2018,1
207,Philippines,country,0,0,0,200.000000,1880,0
208,Poland,country,0,0,0,200.000000,1880,0
209,Portugal,country,0,0,0,200.000000,1880,0
210,Qatar,country,0,0,0,200.000000,1880,0
211,Romania,country,46,46,0,200.000000,1928,8
212,Russia,country,104,104,0,200.000000,2000,17
213,Rwanda,country,10,10,0,200.000000,1951,2
214,Kitts,country,0,0,0,200.000000,1880,0
215,Nevis,country,10,10,0,200.000000,1922,2
216,Lucia,country,59426,59335,91,199.387473,2009,146
217,Vincent,country,364716,1420,363296,198.442624,1971,146
218,Grenadines,country,0,0,0,200.000000,1880,0
219,Samoa,country,0,0,0,200.000000,1880,0
220,Marino,country,2231,0,2231,200.000000,1981,113
221,SaoTome,country,0,0,0,200.000000,1880,0
222,Scotland,country,996,724,272,90.763052,2018,37
223,Principe,country,0,0,0,200.000000,1880,0
224,SaudiArabia,country,0,0,0,200.000000,1880,0
225,Senegal,country,0,0,0,200.000000,1880,0
226,Serbia,country,0,0,0,200.000000,1880,0
227,Seychelles,country,0,0,0,200.000000,1880,0
228,Leone,country,6637,6182,455,172.577972,1920,125
229,Singapore,country,0,0,0,200.000000,1880,0
230,Slovakia,country,0,0,0,200.000000,1880,0
231,Slovenia,country,0,0,0,200.000000,1880,0
232,Solomon,country,38080,11,38069,199.884454,1997,146
233,Somalia,country,114,114,0,200.000000,1993,11
234,Spain,country,0,0,0,200.000000,1880,0
235,SriLanka,country,0,0,0,200.000000,1880,0
236,Sudan,country,10,0,10,200.000000,1982,2
237,Suriname,country,0,0,0,200.000000,1880,0
238,Sweden,country,78,78,0,200.000000,2016,12
239,Switzerland,country,0,0,0,200.000000,1880,0
240,Syria,country,567,567,0,200.000000,2006,42
241,Taiwan,country,913,71,842,168.893757,1986,54
242,Tajikistan,country,0,0,0,200.000000,1880,0
243,Tanzania,country,667,667,0,200.000000,1992,40
244,Thailand,country,184,16,168,165.217391,2014,20
245,TimorLeste,country,0,0,0,200.000000,1880,0
246,Togo,country,0,0,0,200.000000,1880,0
247,Tonga,country,159,159,0,200.000000,1968,17
248,Trinidad,country,9720,4354,5366,20.823045,1950,133
249,Tobago,country,0,0,0,200.000000,1880,0
250,Tunisia,country,596,596,0,200.000000,1978,34
251,Turkey,country,0,0,0,200.000000,1880,0
252,Turkmenistan,country,0,0,0,200.000000,1880,0
253,Tuvalu,country,0,0,0,200.000000,1880,0
254,Uganda,country,58,46,12,117.241379,1975,7
255,Ukraine,country,0,0,0,200.000000,1880,0
256,Arab,country,0,0,0,200.000000,1880,0
257,Kingdom,country,381,0,381,200.000000,2020,17
258,Britain,country,1533,712,821,14.220483,2008,53
259,England,country,320,260,60,125.000000,2016,26
260,States,country,0,0,0,200.000000,1880,0
261,Uruguay,country,0,0,0,200.000000,1880,0
262,Uzbekistan,country,0,0,0,200.000000,1880,0
263,Vanuatu,country,0,0,0,200.000000,1880,0
264,Vatican,country,0,0,0,200.000000,1880,0
265,Venezuela,country,0,0,0,200.000000,1880,0
266,Vietnam,country,0,0,0,200.000000,1880,0
267,Wales,country,38,0,38,200.000000,1930,7
268,Yemen,country,0,0,0,200.000000,1880,0
269,Zambia,country,0,0,0,200.000000,1880,0
270,Zimbabwe,country,5,0,5,200.000000,1981,1
271,Kosovo,country,0,0,0,200.000000,1880,0
272,Sahara,country,4734,4729,5,199.577524,2008,57

In [ ]:
pd.set_option('display.max_rows', None)
country_names = geo_names[geo_names["type"] == "country"]
country_names = country_names[country_names["count"] > 0]
# salvador, holland, zealand, korea, nevis, lucia, vincent, marino, leone, solomon, kingdom
replacements = {"Salvador" : "El Salvador", "Holland" : "Netherlands", "Zealand" : "New Zealand",
                "Korea" : "South Korea", "Nevis" : "Saint Kitts and Nevis", "Lucia" : "Saint Lucia",
                "Vincent" : "Saint Vincent", "Marino" : "San Marino", "Leone" : "Sierra Leone",
                "Solomon" : "Solomon Islands", "Marshall" : "Marshall Islands", "Kingdom" : "United Kingdom", "Ivory" : "Ivory Coast"}
country_names["name"] = country_names["name"].replace(replacements)
country_names

,name,type,count,f_count,m_count,per_diff,center_year,years
70,Algeria,country,32,32,0,200.000000,1994,6
75,Argentina,country,442,442,0,200.000000,1963,65
76,Armenia,country,163,163,0,200.000000,1921,23
77,Australia,country,350,339,11,187.428571,1932,47
78,Austria,country,17,17,0,200.000000,1992,3
86,Belize,country,85,85,0,200.000000,2018,13
89,Bolivia,country,5,5,0,200.000000,1990,1
93,Brazil,country,722,653,69,161.772853,2014,32
101,Canada,country,54,54,0,200.000000,1995,10
103,Chad,country,241767,1039,240728,198.280990,1978,111
105,China,country,4618,4608,10,199.133824,1993,118
111,Cuba,country,616,569,47,169.480519,1922,58
112,Cyprus,country,302,21,281,172.185430,2019,21
114,Denmark,country,5,0,5,200.000000,1970,1
116,Dominica,country,2338,2338,0,200.000000,1982,110
118,Egypt,country,5546,4726,820,140.858276,2017,42
119,El Salvador,country,49788,183,49605,198.529766,1987,130
121,Eritrea,country,11,11,0,200.000000,2021,2
124,Ethiopia,country,6,6,0,200.000000,2022,1
126,Finland,country,12,0,12,200.000000,2021,2
127,France,country,1538,1159,379,101.430429,1939,88
130,Georgia,country,167019,166290,729,198.254091,1943,146
131,Germany,country,723,517,206,86.030429,2012,41
132,Ghana,country,12,12,0,200.000000,1969,2
139,Haiti,country,50,50,0,200.000000,2018,8
142,Iceland,country,109,98,11,159.633028,2023,9
143,India,country,24017,23990,27,199.550319,1997,146
144,Indonesia,country,83,83,0,200.000000,1997,10
145,Iran,country,1775,416,1359,106.253521,1993,84
147,Ireland,country,6556,6347,209,187.248322,2009,51
148,Israel,country,72874,1637,71237,191.014628,2003,146
149,Italy,country,2230,2220,10,198.206278,2016,40
150,Ivory Coast,country,23114,14546,8568,51.726227,1987,145
151,Jamaica,country,1569,1532,37,190.567240,1992,53
153,Jordan,country,536795,135599,401196,98.956585,1998,145
155,Kenya,country,27553,25412,2141,168.918085,1993,73
164,Libya,country,14,14,0,200.000000,2011,2
170,Malaysia,country,11031,11031,0,200.000000,2015,39
172,Mali,country,1495,1406,89,176.187291,2011,52
173,Malta,country,55,55,0,200.000000,1920,9
174,Marshall Islands,country,98604,1157,97447,195.306478,1964,146
180,Monaco,country,82,33,49,39.024390,2024,4
183,Morocco,country,165,6,159,185.454545,2020,14
190,Netherlands,country,11007,7835,3172,84.727900,2015,124
191,New Zealand,country,997,72,925,171.113340,2021,24
193,Niger,country,36,25,11,77.777778,1977,5
194,Nigeria,country,810,810,0,200.000000,1999,46
195,South Korea,country,298,298,0,200.000000,2006,34
198,Oman,country,45,0,45,200.000000,1973,8
201,Palestine,country,169,169,0,200.000000,1931,25
205,Peru,country,5,5,0,200.000000,2018,1
210,Romania,country,46,46,0,200.000000,1928,8
211,Russia,country,104,104,0,200.000000,2000,17
212,Rwanda,country,10,10,0,200.000000,1951,2
214,Saint Kitts and Nevis,country,10,10,0,200.000000,1922,2
215,Saint Lucia,country,59426,59335,91,199.387473,2009,146
216,Saint Vincent,country,364716,1420,363296,198.442624,1971,146
219,San Marino,country,2231,0,2231,200.000000,1981,113
226,Sierra Leone,country,6637,6182,455,172.577972,1920,125
230,Solomon Islands,country,38080,11,38069,199.884454,1997,146
231,Somalia,country,114,114,0,200.000000,1993,11
234,Sudan,country,10,0,10,200.000000,1982,2
236,Sweden,country,78,78,0,200.000000,2016,12
238,Syria,country,567,567,0,200.000000,2006,42
239,Taiwan,country,913,71,842,168.893757,1986,54
241,Tanzania,country,667,667,0,200.000000,1992,40
242,Thailand,country,184,16,168,165.217391,2014,20
245,Tonga,country,159,159,0,200.000000,1968,17
246,Trinidad,country,9720,4354,5366,20.823045,1950,133
248,Tunisia,country,596,596,0,200.000000,1978,34
252,Uganda,country,58,46,12,117.241379,1975,7
255,United Kingdom,country,381,0,381,200.000000,2020,17
256,Britain,country,1533,712,821,14.220483,2008,53
266,Zimbabwe,country,5,0,5,200.000000,1981,1
268,Sahara,country,4734,4729,5,199.577524,2008,57

In [ ]:
import plotly.express as px
fig = px.choropleth(country_names[["name", "count"]],
                    locations='name',          
                    locationmode='country names',
                    color = 'count', # column with the values
                    color_continuous_scale='portland', # this is a nice color
                    labels={'value': 'Value'},
                    range_color=[0, 3000],
                    title='Use of Countries as Names in the US') # title
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0}) # makes it display bigger
fig.show()

In [ ]:
geo_names[geo_names["type"] == "almost_country"]
# add almost countries, and uk countries like scotland, britain

,name,type,count,f_count,m_count,per_diff,center_year,years
273,icelyn,almost_country,303,303,0,200.000000,2023,14
274,icelynn,almost_country,974,974,0,200.000000,2024,19
275,scotlyn,almost_country,1385,1385,0,200.000000,2019,30
276,scotlynn,almost_country,583,583,0,200.000000,2020,24
277,irelyn,almost_country,1594,1594,0,200.000000,2012,29
278,irelynn,almost_country,1740,1740,0,200.000000,2014,28
279,thailyn,almost_country,105,95,10,161.904762,2010,15
280,thailynn,almost_country,21,21,0,200.000000,2016,4

In [ ]:
geo_names[geo_names["type"] == "geo"]

        name type   count  f_count  m_count    per_diff  center_year  years
0      coast  geo     852       87      765  159.154930         2024     12
1       lake  geo    3924      937     2987  104.485219         2008    110
2    lakelyn  geo    3014     2969       45  194.027870         2021     29
3   lakelynn  geo    2652     2652        0  200.000000         2023     24
4      ocean  geo    8233     3822     4411   14.308272         2020     41
5      river  geo   59351    19675    39676   67.399033         2019     46
6      brook  geo   14021    10630     3391  103.259397         1989     95
7     brooke  geo  200521   198491     2030  195.950549         1997    107
8     brooks  geo   59639     1693    57946  188.645014         2019    143
9       isla  geo   58271    58252       19  199.869575         2020    119
10     islay  geo     378      378        0  200.000000         2020     21
11       rio  geo    7812     2282     5530   83.154122         2018     64
12    valley  geo     935      879       56  176.042781         2022     54
13       bay  geo     727      523      204   87.757909         2013     39
14     delta  geo    4476     4368      108  190.348525         1956    142
15      cove  geo    1696      472     1224   88.679245         2022     24
16      loch  geo      90        0       90  200.000000         2019     12
17     marsh  geo     414       11      403  189.371981         1950     55
18    marsha  geo  104442   104191      251  199.038701         1954    116
19       sea  geo      21       10       11    9.523810         1985      4
20      tide  geo      19        0       19  200.000000         2021      3
21     bayou  geo      14        0       14  200.000000         2024      2
22     fjord  geo      15        0       15  200.000000         2020      2
23      mesa  geo     843      843        0  200.000000         2012     43
24    sierra  geo  100866   100597      269  198.933238         1999     82
25     ridge  geo    7911       18     7893  199.089875         2018     46
26      hill  geo     577        0      577  200.000000         1932     70
27     knoll  geo      12        0       12  200.000000         2015      2
28    canyon  geo    4086      259     3827  174.645130         2010     49
29     gorge  geo    2609        0     2609  200.000000         1975    108
30    ravine  geo       5        5        0  200.000000         1990      1
31     basin  geo      13        0       13  200.000000         2020      2
32      cape  geo      24        0       24  200.000000         2023      3
33      reef  geo    1353       63     1290  181.374723         2015     30
34   prairie  geo     501      501        0  200.000000         2016     40
35   savanna  geo   32989    32974       15  199.818121         2003     60
36  savannah  geo  191736   191514      222  199.536863         2005    146
37    tundra  geo      36       36        0  200.000000         1970      6
38   glacier  geo      21       11       10    9.523810         2021      4
39      dune  geo     108        5      103  181.481481         2023      7
40    meadow  geo   12355    12343       12  199.611493         2018     53
41     woods  geo     699       11      688  193.705293         2022     21
42   forrest  geo   54697     1058    53639  192.262830         1958    146
43    forest  geo   18377      593    17784  187.092561         1951    146
44    island  geo     807      698      109  145.972739         2020     27
45     terra  geo   15434    15429        5  199.870416         1983     85
46     beach  geo       5        0        5  200.000000         1915      1
47   channel  geo    1524     1524        0  200.000000         1990     56
48     cliff  geo    9307        0     9307  200.000000         1961    146
49     shoal  geo       5        0        5  200.000000         2022      1
50      rock  geo    2681        0     2681  200.000000         1963     97
51     rocky  geo   29134      447    28687  193.862841         1975    113
52     stone  geo    6831      155     6676  190.923730         2008     53
53      crag  geo       5        0        5  200.000000         1975      1
54       bar  geo      50       23       27   16.000000         2011      8
55     gorge  geo    2609        0     2609  200.000000         1975    108
56     levee  geo     134       84       50   50.746269         2021     11
57      vale  geo     539      340      199   52.319109         2018     27
58    alpine  geo       7        7        0  200.000000         1920      1
59     oasis  geo     383      305       78  118.537859         2019     26
60    summit  geo    1271      247     1024  122.265932         2020     26
61      dale  geo  300043    21887   278156  170.821516         1953    145
62      dell  geo    6552     2544     4008   44.688645         1944    139
63      glen  geo  127054     1348   125706  195.756135         1952    146
64     glenn  geo  250778     2136   248642  196.593003         1953    146
65    glenna  geo   25629    25624        5  199.921963         1942    145
66   terrace  geo     821      107      714  147.868453         1975     61
67     taiga  geo     366       11      355  187.978142         2013     29

In [ ]:
geo_names[geo_names["type"] == "direction"]

      name       type  count  f_count  m_count    per_diff  center_year  years
281  north  direction    407       74      333  127.272727         2013     34
282   east  direction     85        5       80  176.470588         2022      8
283  south  direction     11        0       11  200.000000         2025      2
284   west  direction   3720       28     3692  196.989247         1994    146

In [ ]:
pd.set_option('display.max_rows', None)
city_names = geo_names[geo_names["type"] == "city"]
city_names

,name,type,count,f_count,m_count,per_diff,center_year,years
290,York,city,966,11,955,195.445135,1966,104
291,Angeles,city,3498,3421,77,191.194969,2004,75
292,Chicago,city,175,54,121,76.571429,2022,14
293,Houston,city,18540,436,18104,190.593312,1992,146
294,Toronto,city,49,0,49,200.000000,1974,8
295,Miami,city,349,343,6,193.123209,2012,31
296,Francisco,city,143146,954,142192,197.334190,1992,146
297,Seattle,city,132,127,5,184.848485,2003,19
298,Boston,city,11944,1043,10901,165.070328,2013,103
299,Atlanta,city,699,699,0,200.000000,1999,56
300,Dallas,city,87085,15882,71203,127.050583,1996,146
301,Montreal,city,1113,0,1113,200.000000,1994,56
302,Vancouver,city,0,0,0,200.000000,1880,0
303,Vegas,city,473,145,328,77.378436,2011,30
304,Denver,city,23413,4235,19178,127.647034,1998,135
305,Phoenix,city,40635,16064,24571,41.870309,2016,53
306,Minneapolis,city,0,0,0,200.000000,1880,0
307,Detroit,city,148,0,148,200.000000,1924,22
308,Havana,city,1604,1604,0,200.000000,2016,39
309,Panama,city,0,0,0,200.000000,1880,0
310,Bogota,city,0,0,0,200.000000,1880,0
311,Lima,city,190,190,0,200.000000,1929,30
312,Santiago,city,103965,137,103828,199.472900,2016,141
313,Caracas,city,0,0,0,200.000000,1880,0
314,London,city,54779,44455,10324,124.613447,2013,110
315,Paris,city,42923,33663,9260,113.705939,2005,141
316,Berlin,city,3431,1796,1635,9.385019,2004,114
317,Madrid,city,42,37,5,152.380952,2004,8
318,Rome,city,6075,503,5572,166.880658,2020,112
319,Amsterdam,city,0,0,0,200.000000,1880,0
320,Barcelona,city,0,0,0,200.000000,1880,0
321,Vienna,city,7565,7565,0,200.000000,2017,117
322,Prague,city,0,0,0,200.000000,1880,0
323,Warsaw,city,0,0,0,200.000000,1880,0
324,Budapest,city,0,0,0,200.000000,1880,0
325,Stockholm,city,0,0,0,200.000000,1880,0
326,Copenhagen,city,0,0,0,200.000000,1880,0
327,Helsinki,city,0,0,0,200.000000,1880,0
328,Oslo,city,581,0,581,200.000000,2022,18
329,Zurich,city,143,0,143,200.000000,2018,17
330,Geneva,city,89067,88758,309,198.612281,1929,146
331,Brussels,city,0,0,0,200.000000,1880,0
332,Lisbon,city,16,11,5,75.000000,2017,3
333,Athens,city,218,55,163,99.082569,2019,20
334,Munich,city,0,0,0,200.000000,1880,0
335,Hamburg,city,0,0,0,200.000000,1880,0
336,Frankfurt,city,0,0,0,200.000000,1880,0
337,Milan,city,28165,9557,18608,64.271259,2015,122
338,Naples,city,0,0,0,200.000000,1880,0
339,Venice,city,3232,2946,286,164.603960,1966,130
340,Florence,city,340547,339093,1454,198.292159,1920,146
341,Edinburgh,city,0,0,0,200.000000,1880,0
342,Dublin,city,462,128,334,89.177489,2013,22
343,Reykjavik,city,0,0,0,200.000000,1880,0
344,Kyiv,city,0,0,0,200.000000,1880,0
345,Moscow,city,0,0,0,200.000000,1880,0
346,Istanbul,city,0,0,0,200.000000,1880,0
347,Ankara,city,0,0,0,200.000000,1880,0
348,Sofia,city,186931,186744,187,199.599852,2014,141
349,Sarajevo,city,0,0,0,200.000000,1880,0
350,Riga,city,0,0,0,200.000000,1880,0
351,Tallinn,city,7,7,0,200.000000,2024,1
352,Vilnius,city,0,0,0,200.000000,1880,0
353,Minsk,city,0,0,0,200.000000,1880,0
354,Yerevan,city,0,0,0,200.000000,1880,0
355,Tirana,city,0,0,0,200.000000,1880,0
356,Luxembourg,city,0,0,0,200.000000,1880,0
357,Dubai,city,13,0,13,200.000000,2019,2
358,Riyadh,city,63,0,63,200.000000,2009,10
359,Jeddah,city,0,0,0,200.000000,1880,0
360,Doha,city,164,153,11,173.170732,2009,23
361,Beirut,city,0,0,0,200.000000,1880,0
362,Damascus,city,129,0,129,200.000000,2001,22
363,Baghdad,city,0,0,0,200.000000,1880,0
364,Tehran,city,124,5,119,183.870968,1980,16
365,Amman,city,87,0,87,200.000000,2001,11
366,Jerusalem,city,478,329,149,75.313808,2014,35
367,Muscat,city,0,0,0,200.000000,1880,0
368,Sanaa,city,6146,6146,0,200.000000,2009,44
369,Cairo,city,9999,584,9415,176.637664,2021,40
370,Lagos,city,0,0,0,200.000000,1880,0
371,Nairobi,city,1596,1561,35,191.228070,2021,40
372,Casablanca,city,0,0,0,200.000000,1880,0
373,Accra,city,0,0,0,200.000000,1880,0
374,Kinshasa,city,122,116,6,180.327869,1977,11
375,Algiers,city,0,0,0,200.000000,1880,0
376,Mumbai,city,0,0,0,200.000000,1880,0
377,Delhi,city,0,0,0,200.000000,1880,0
378,Karachi,city,0,0,0,200.000000,1880,0
379,Colombo,city,0,0,0,200.000000,1880,0
380,Tokyo,city,116,89,27,106.896552,2022,9
381,Beijing,city,0,0,0,200.000000,1880,0
382,Shanghai,city,0,0,0,200.000000,1880,0
383,Seoul,city,25,16,9,56.000000,2024,4
384,HongKong,city,0,0,0,200.000000,1880,0
385,Taipei,city,0,0,0,200.000000,1880,0
386,Osaka,city,0,0,0,200.000000,1880,0
387,Kyoto,city,0,0,0,200.000000,1880,0
388,Wuhan,city,0,0,0,200.000000,1880,0
389,Singapore,city,0,0,0,200.000000,1880,0
390,Bangkok,city,0,0,0,200.000000,1880,0
391,Manila,city,214,214,0,200.000000,1898,14
392,Hanoi,city,0,0,0,200.000000,1880,0
393,Vientiane,city,0,0,0,200.000000,1880,0
394,Bali,city,254,212,42,133.858268,2021,18
395,Sydney,city,187700,178296,9404,179.959510,2001,146
396,Melbourne,city,1012,0,1012,200.000000,1927,59
397,Brisbane,city,0,0,0,200.000000,1880,0
398,Perth,city,0,0,0,200.000000,1880,0
399,Auckland,city,0,0,0,200.000000,1880,0
400,Wellington,city,2879,0,2879,200.000000,1949,140
401,Adelaide,city,35007,35007,0,200.000000,2009,146
402,Monaco,city,82,33,49,39.024390,2024,4

In [ ]:
continent_names = geo_names[geo_names["type"] == "continent"]
continent_names = pd.concat([continent_names, geo_names[geo_names["name"] == "Australia"]])
continent_names

,name,type,count,f_count,m_count,per_diff,center_year,years
273,america,continent,13538,13522,16,199.527257,2004,146
274,europe,continent,15,15,0,200.000000,2021,2
275,asia,continent,32687,32491,196,197.601493,1999,67
276,africa,continent,1042,1042,0,200.000000,1985,57
277,antarctica,continent,0,0,0,200.000000,1880,0
77,Australia,country,350,339,11,187.428571,1932,47

In [ ]:
calculate_spread("Oceania")

(2006, 12, 200, np.int64(78), np.int64(0))

In [ ]:
geo_names[geo_names["type"] == "planet"]

        name    type  count  f_count  m_count    per_diff  center_year  years
398  mercury  planet    300       94      206   74.666667         2018     25
399    venus  planet  10057     9956      101  195.982897         1974    139
400    earth  planet     58       46       12  117.241379         2020      8
401     mars  planet   1522      202     1320  146.911958         2021     36
402  jupiter  planet   1749     1099      650   51.343625         2021     23
403   saturn  planet    157      107       50   72.611465         2022     11
404   uranus  planet      5        5        0  200.000000         1969      1
405  neptune  planet     24        0       24  200.000000         2022      3
406    pluto  planet     23        0       23  200.000000         2024      3
407     moon  planet    627      465      162   96.650718         2021     26
408     luna  planet  87834    87715      119  199.458069         2020    133

In [ ]:
geo_names[geo_names["type"] == "named_feature"]

,name,type,count,f_count,m_count,per_diff,center_year,years
409,everest,named_feature,3986,928,3058,106.874059,2020,48
410,yosemite,named_feature,5,5,0,200.000000,1993,1
411,mckinley,named_feature,22884,13098,9786,28.945988,2008,136
412,denali,named_feature,2479,1795,684,89.632916,2013,40
413,rainier,named_feature,920,46,874,180.000000,2012,57
414,etna,named_feature,681,681,0,200.000000,1915,66
415,vesuvius,named_feature,0,0,0,200.000000,1880,0

## Extinct Names
Finding names that used to be used but no longer are at four levels:
- Vulnerable -- names in the top 1,000 from 1945 or earlier with 50 or less per year since 1960
- Endangered -- names in the top 1,000 from 1945 or earlier with 20 or less per year since 1960
- Critically Endangered -- names in the top 1,000 from 1945 or earlier with 10 or less per year since 1960
- Extinct -- names in the top 1,000 from 1945 or earlier with no uses since 1960

In [43]:
f_top_1000_25 = set() # female names from top 1,000 from 1925 or earlier
m_top_1000_25 = set()
names_25 = {"f" : f_top_1000_25, "m" : m_top_1000_25}
f_top_1000_45 = set() # female names from top 1,000 from 1945 or earlier
m_top_1000_45 = set()
names_45 = {"f" : f_top_1000_45, "m" : m_top_1000_45}
ranks = ["extinct", "crit", "endangered", "vulnerable", "fine"]

In [44]:
for sex in ["f", "m"]:
    for year in range(min_data_year, 1926):
        curr_list = names_25[sex]
        names = fun.get_year_list_one(sex, year)
        names = names.iloc[0:1000]
        curr_list.update(list(names["Name"]))

In [45]:
for sex in ["f", "m"]:
    for year in range(min_data_year, 1946):
        curr_list = names_45[sex]
        names = fun.get_year_list_one(sex, year)
        names = names.iloc[0:1000]
        curr_list.update(list(names["Name"]))

In [52]:
def names_sorter(sex, all_names, min_y=min_data_year, max_y=max_data_year):
    """Checks if the counts of a name across min_y to max_y are less than a number"""
    endangered = pd.DataFrame(columns = ["Name", "Sex", "Rating", "Count"])
    candidate_names = {x : 0 for x in all_names} # 0 = extinct
    for year in range(min_y, max_y): # iterate over years name must follow criteria
        year_list = fun.get_year_list_one(sex, year)
        for n in list(candidate_names): # iterate over names
            if n in list(year_list["Name"]):
                count = year_list[year_list["Name"] == n]["Count"].sum() 
            else:
                count = 0
            current_rank = candidate_names[n]
            if count < 5 and current_rank < 1:
                pass
            elif count <= 10 and current_rank < 2:
                candidate_names[n] = 1 # critically endangered
            elif count <= 20 and current_rank < 3:
                candidate_names[n] = 2 # endangered
            elif count <= 50 and current_rank < 4:
                candidate_names[n] = 3 # vulnerable
            else:
                candidate_names[n] = 4 # fine
    for n, r in candidate_names.items():
        if r != 4:
            total_count = fun.name_counts_simple(n, sex)[0]
            endangered.loc[len(endangered)] = [n, sex, ranks[r], total_count]
    return endangered

In [53]:
endangered_f_60 = names_sorter("f", f_top_1000_25, 1960, max_data_year)

In [54]:
endangered_m_60 = names_sorter("m", m_top_1000_25, 1960, max_data_year)

In [56]:
pd.set_option('display.max_rows', None)
print(endangered_f_60[endangered_f_60["Rating"] == "extinct"].sort_values(by="Count", ascending=False))

             Name Sex   Rating  Count
651        goldia   f  extinct   1860
725          myrl   f  extinct   1831
325      elfrieda   f  extinct   1487
224        cleone   f  extinct   1320
825       mafalda   f  extinct   1279
63          beula   f  extinct   1183
335        hessie   f  extinct   1118
273        maymie   f  extinct   1054
234          bula   f  extinct   1034
549        mettie   f  extinct   1031
738         orene   f  extinct   1015
674       gladyce   f  extinct   1006
807         buena   f  extinct    987
111        zelpha   f  extinct    956
70         birtie   f  extinct    946
462           imo   f  extinct    903
442       alverda   f  extinct    891
840        clella   f  extinct    887
502        vlasta   f  extinct    873
157       luverne   f  extinct    847
488       maebell   f  extinct    823
684         macel   f  extinct    821
810        doshie   f  extinct    799
523        fronie   f  extinct    789
881         nanie   f  extinct    778
244        eathel   f  extinct    763
618          eola   f  extinct    740
146         lutie   f  extinct    735
909        hildur   f  extinct    718
907          orma   f  extinct    699
593         versa   f  extinct    688
51         modena   f  extinct    683
262         besse   f  extinct    671
153         altie   f  extinct    650
371          murl   f  extinct    626
632        littie   f  extinct    623
765        girtha   f  extinct    597
288         helma   f  extinct    595
58           lota   f  extinct    586
119      capitola   f  extinct    579
863         gusta   f  extinct    578
232         lular   f  extinct    572
20         zilpha   f  extinct    570
702         corda   f  extinct    567
734        sister   f  extinct    563
245         cleva   f  extinct    561
327        virdie   f  extinct    555
767         dewey   f  extinct    547
210        fronia   f  extinct    543
158        dillie   f  extinct    537
139         manie   f  extinct    529
204         elgie   f  extinct    529
364        ermine   f  extinct    522
865        vessie   f  extinct    513
240         ellar   f  extinct    511
317           ura   f  extinct    508
594          oral   f  extinct    506
311         pluma   f  extinct    506
753         nobie   f  extinct    496
339        fannye   f  extinct    486
913         eller   f  extinct    481
123          ruie   f  extinct    470
338           exa   f  extinct    466
404        lockie   f  extinct    464
620        mintie   f  extinct    446
198        ethyle   f  extinct    437
461        beadie   f  extinct    435
191         fleda   f  extinct    432
451          opha   f  extinct    427
802        parlee   f  extinct    414
755         hasel   f  extinct    400
586         vinie   f  extinct    381
403         oline   f  extinct    377
458        leaner   f  extinct    373
531         lempi   f  extinct    367
405        prudie   f  extinct    354
515         venie   f  extinct    345
460       cliffie   f  extinct    343
512        liller   f  extinct    333
683          beda   f  extinct    328
538         tiney   f  extinct    327
449        gillie   f  extinct    321
0           elfie   f  extinct    316
434         orrie   f  extinct    313
631        tishie   f  extinct    312
757       alwilda   f  extinct    312
640          effa   f  extinct    312
818        clytie   f  extinct    301
744          edla   f  extinct    300
465          luda   f  extinct    276
13          lemma   f  extinct    262
519        biddie   f  extinct    262
471          olar   f  extinct    254
823          byrd   f  extinct    253
173         epsie   f  extinct    251
249      josefita   f  extinct    244
200        dezzie   f  extinct    242
384        mirtie   f  extinct    236
439          irva   f  extinct    229
331        orilla   f  extinct    225
96            ica   f  extinct    223
92         hennie   f  extinct    219
687           ota   f  extinct    215
793        manila   f  extinct    214
277       fronnie   f  extinct    213
110        elmire   f  extinct    213
510        clemie   f  extinct    211
12          ragna   f  extinct    201
430         leafy   f  extinct    197
102       pairlee   f  extinct    187
263         arkie   f  extinct    183
330        pallie   f  extinct    176
853       octavie   f  extinct    176
857      birdella   f  extinct    173
382        cornie   f  extinct    172
126        alzina   f  extinct    170
1            loda   f  extinct    166
178        rettie   f  extinct    163
572        clemma   f  extinct    161
271          octa   f  extinct    160
697       aurilla   f  extinct    153
125         metha   f  extinct    149
481        sibbie   f  extinct    139
741        ninnie   f  extinct    136
55           orra   f  extinct    129
514       manilla   f  extinct    124
650          bird   f  extinct    121
142        clevie   f  extinct    119
708         gunda   f  extinct    118
610        gustie   f  extinct    106
597          vicy   f  extinct    101
832        caddie   f  extinct     96
905      minervia   f  extinct     95
796        grover   f  extinct     92
811         lidie   f  extinct     91
602         ethie   f  extinct     86
727         tinie   f  extinct     83
780         ednah   f  extinct     75
908        rillie   f  extinct     69
790          oney   f  extinct     61
255         dosia   f  extinct     61
21          affie   f  extinct     60
736       manerva   f  extinct     60
788        siddie   f  extinct     59
456     theodocia   f  extinct     54
891          ason   f  extinct     41
490      manervia   f  extinct     40
503        neppie   f  extinct     38
344        alwine   f  extinct     25
201  francisquita   f  extinct     21
441        sannie   f  extinct     21
165        alwina   f  extinct     18
436         crete   f  extinct     14
134         franc   f  extinct     10
74         zilpah   f  extinct      9

In [57]:
pd.set_option('display.max_rows', None)
print(endangered_m_60[endangered_m_60["Rating"] == "extinct"].sort_values(by="Count", ascending=False))

           Name Sex   Rating  Count
177     luverne   m  extinct   1067
847       ewald   m  extinct    922
74        elsie   m  extinct    886
345        eino   m  extinct    814
153       hideo   m  extinct    805
854      minnie   m  extinct    787
283     woodroe   m  extinct    784
730      selmer   m  extinct    759
154     lucille   m  extinct    750
427      bessie   m  extinct    737
783        opal   m  extinct    718
600      minoru   m  extinct    675
815      nellie   m  extinct    593
232    gertrude   m  extinct    568
905       toivo   m  extinct    535
365     pinkney   m  extinct    531
258       metro   m  extinct    522
762      myrtle   m  extinct    498
378      hattie   m  extinct    494
852     adelard   m  extinct    488
294       agnes   m  extinct    465
397       eliga   m  extinct    434
489       viola   m  extinct    434
638       aloys   m  extinct    414
967       mabel   m  extinct    409
829     erastus   m  extinct    407
1006      posey   m  extinct    396
78       doctor   m  extinct    379
636    coolidge   m  extinct    372
324      fannie   m  extinct    369
5         waino   m  extinct    347
393        lula   m  extinct    339
838      burrel   m  extinct    339
732        eula   m  extinct    332
890       abbie   m  extinct    330
46         floy   m  extinct    323
160    gottlieb   m  extinct    320
790        harm   m  extinct    320
1001  littleton   m  extinct    312
350         oda   m  extinct    301
423       leona   m  extinct    294
779     bluford   m  extinct    293
812        wirt   m  extinct    286
386       hymen   m  extinct    285
189        less   m  extinct    281
141       mamie   m  extinct    278
225        lola   m  extinct    275
431       miner   m  extinct    274
257       oland   m  extinct    274
17         birt   m  extinct    268
565     council   m  extinct    263
152         ebb   m  extinct    247
536        flem   m  extinct    244
745       press   m  extinct    241
529       ovila   m  extinct    240
336      winnie   m  extinct    228
603     blanche   m  extinct    223
349       bynum   m  extinct    223
696      tatsuo   m  extinct    222
7        beulah   m  extinct    213
874     hjalmer   m  extinct    202
340     pearley   m  extinct    178
436       genie   m  extinct    173
863        thos   m  extinct    166
982      ignatz   m  extinct    158
587       offie   m  extinct    151
541         ell   m  extinct    144
820       almus   m  extinct    143
392       della   m  extinct    139
586         sie   m  extinct    133
665       maude   m  extinct    133
399       grove   m  extinct    124
778        dorr   m  extinct    124
29       greene   m  extinct    121
652       alver   m  extinct    119
621     shafter   m  extinct    119
331       fount   m  extinct    118
236        alta   m  extinct    117
407      emmons   m  extinct    117
138     delphin   m  extinct    116
749     hjalmar   m  extinct    115
674        ewin   m  extinct    115
165      ambers   m  extinct    113
763       elick   m  extinct    113
816      tallie   m  extinct    112
744        bird   m  extinct    109
995        olof   m  extinct    107
36         dink   m  extinct    107
607         add   m  extinct    102
618      lizzie   m  extinct    102
862        math   m  extinct    100
988        atha   m  extinct     99
892         abb   m  extinct     96
640     alphons   m  extinct     90
461      ceylon   m  extinct     86
465         ott   m  extinct     84
858        purl   m  extinct     81
327        polk   m  extinct     80
38           ah   m  extinct     74
994         obe   m  extinct     73
49          fed   m  extinct     72
672      goebel   m  extinct     70
993        foch   m  extinct     67
785       hence   m  extinct     66
426     hosteen   m  extinct     65
881     benjman   m  extinct     58
843    thorwald   m  extinct     54
133      severt   m  extinct     53
817       algot   m  extinct     53
902       virge   m  extinct     52
784        arba   m  extinct     47
760       clabe   m  extinct     45
472       amasa   m  extinct     37
250        maud   m  extinct     31
308         lim   m  extinct     30
111         ham   m  extinct     29
512         nim   m  extinct     28
326        esta   m  extinct     27
631        lish   m  extinct     24
725        doll   m  extinct     24
984        bose   m  extinct     20
448       rhoda   m  extinct     12
947        lone   m  extinct     11
394      schley   m  extinct     10
827        bunk   m  extinct     10
605         edw   m  extinct      6
937        roll   m  extinct      5

In [58]:
endangered_f_85 = names_sorter("f", f_top_1000_45, 1985, max_data_year)

In [59]:
endangered_m_85 = names_sorter("m", m_top_1000_45, 1985, max_data_year)

In [60]:
pd.set_option('display.max_rows', None)
print(endangered_f_85[endangered_f_85["Rating"] == "extinct"].sort_values(by="Count", ascending=False))

              Name Sex   Rating  Count
1237           gay   f  extinct  17985
18          dortha   f  extinct   6811
54            floy   f  extinct   6612
598         blanch   f  extinct   6420
860       hortense   f  extinct   6313
1247         verla   f  extinct   6190
621           gaye   f  extinct   5746
297          hulda   f  extinct   5407
33         dorotha   f  extinct   4788
495      gearldine   f  extinct   4686
1200       florene   f  extinct   4616
367         vergie   f  extinct   4582
1235        myrtie   f  extinct   4401
483       georgene   f  extinct   4354
146        myrtice   f  extinct   4342
149          velva   f  extinct   4274
1097        estell   f  extinct   4232
1138         sudie   f  extinct   4024
333          cleta   f  extinct   4013
523         vernie   f  extinct   3959
592          clyde   f  extinct   3932
112          marge   f  extinct   3784
800          loyce   f  extinct   3503
769          idell   f  extinct   3425
1224         altha   f  extinct   3365
823         willia   f  extinct   3316
569       berneice   f  extinct   3208
293     bernardine   f  extinct   3128
901         hedwig   f  extinct   3077
975          bulah   f  extinct   3027
1243         hilma   f  extinct   2999
1179       arvilla   f  extinct   2931
75         willene   f  extinct   2928
735          ossie   f  extinct   2917
1222         rutha   f  extinct   2799
341          ludie   f  extinct   2687
416          elois   f  extinct   2642
295         ardell   f  extinct   2635
45          verdie   f  extinct   2614
244        earlean   f  extinct   2585
862           dell   f  extinct   2544
15         alverta   f  extinct   2441
59         phyliss   f  extinct   2406
159          myrle   f  extinct   2405
1145       hildred   f  extinct   2404
704          ethyl   f  extinct   2395
353        merlene   f  extinct   2379
770       glendora   f  extinct   2350
516     hildegarde   f  extinct   2326
279         verlie   f  extinct   2282
110        beaulah   f  extinct   2273
644      albertine   f  extinct   2196
641        mardell   f  extinct   2170
253          emmer   f  extinct   2155
581          inell   f  extinct   2147
965         shelba   f  extinct   2136
71          theola   f  extinct   2099
714        verdell   f  extinct   2085
342       floretta   f  extinct   2071
67           trula   f  extinct   2045
960         delpha   f  extinct   2025
212         birtha   f  extinct   1973
392       pearlene   f  extinct   1958
423          ruthe   f  extinct   1949
263        glennie   f  extinct   1931
1206       dorathy   f  extinct   1928
178           noma   f  extinct   1895
1000       lurline   f  extinct   1885
444        doloris   f  extinct   1885
491        verlene   f  extinct   1874
753          eulah   f  extinct   1871
909         goldia   f  extinct   1860
995       ethelene   f  extinct   1837
1016          myrl   f  extinct   1831
1158        mertie   f  extinct   1830
474         ressie   f  extinct   1823
157        mozella   f  extinct   1823
370           etha   f  extinct   1802
470          clora   f  extinct   1800
756         gertha   f  extinct   1792
683          elmer   f  extinct   1753
52         elberta   f  extinct   1750
587         creola   f  extinct   1742
224         cleora   f  extinct   1712
411         concha   f  extinct   1696
104        margene   f  extinct   1687
547        clarine   f  extinct   1659
591           veva   f  extinct   1598
46         burnice   f  extinct   1593
785           odie   f  extinct   1589
172        hermina   f  extinct   1587
794        dorthey   f  extinct   1559
443         vertie   f  extinct   1543
1003       hermine   f  extinct   1534
1025         irine   f  extinct   1528
1174         margy   f  extinct   1525
101        ardelle   f  extinct   1500
482         allean   f  extinct   1491
448       elfrieda   f  extinct   1487
930          oneta   f  extinct   1465
320         zettie   f  extinct   1458
1045        hertha   f  extinct   1453
88            eura   f  extinct   1453
1228          atha   f  extinct   1441
926           otha   f  extinct   1403
776          cleda   f  extinct   1392
561          monna   f  extinct   1385
291        marolyn   f  extinct   1381
544         buelah   f  extinct   1363
707           osie   f  extinct   1354
432          olene   f  extinct   1347
16          vennie   f  extinct   1339
276          fleta   f  extinct   1333
825         earlie   f  extinct   1329
783         ardath   f  extinct   1326
391            oda   f  extinct   1324
155       blanchie   f  extinct   1323
311         cleone   f  extinct   1320
111         lahoma   f  extinct   1312
1070        vernia   f  extinct   1288
784        shirlie   f  extinct   1288
406       henretta   f  extinct   1286
1141       mafalda   f  extinct   1279
512        elwanda   f  extinct   1272
1187        ardyce   f  extinct   1263
898       vernelle   f  extinct   1245
1020     willodean   f  extinct   1237
667           ozie   f  extinct   1235
371          ether   f  extinct   1214
231         virgia   f  extinct   1208
388          rheta   f  extinct   1200
138         cleola   f  extinct   1196
1162         leoma   f  extinct   1196
759         lossie   f  extinct   1189
176         otelia   f  extinct   1184
90           beula   f  extinct   1183
554          dicie   f  extinct   1167
460         hessie   f  extinct   1118
350         shelva   f  extinct   1117
1033         ozell   f  extinct   1116
998         berdie   f  extinct   1114
917          docia   f  extinct   1109
1192         gerda   f  extinct   1099
395          dorla   f  extinct   1089
1175       flonnie   f  extinct   1065
1011    josiephine   f  extinct   1061
380         maymie   f  extinct   1054
1006        mossie   f  extinct   1051
1085         anner   f  extinct   1037
325           bula   f  extinct   1034
219        joretta   f  extinct   1033
669         ardeth   f  extinct   1033
763         mettie   f  extinct   1031
895        luberta   f  extinct   1016
1032         orene   f  extinct   1015
147         jeffie   f  extinct   1012
943        gladyce   f  extinct   1006
1168          dola   f  extinct    994
1118         buena   f  extinct    987
734          roena   f  extinct    984
181         lassie   f  extinct    979
400          argie   f  extinct    979
152         zelpha   f  extinct    956
486          donie   f  extinct    956
916         tinnie   f  extinct    954
868       francies   f  extinct    952
98          birtie   f  extinct    946
51         elfreda   f  extinct    934
1242        aldona   f  extinct    925
186        loretto   f  extinct    923
633            imo   f  extinct    903
246        edmonia   f  extinct    899
607        alverda   f  extinct    891
1160        clella   f  extinct    887
113          verne   f  extinct    878
922          milda   f  extinct    878
697         vlasta   f  extinct    873
1268         frona   f  extinct    873
281          herma   f  extinct    861
475         clydie   f  extinct    853
208        luverne   f  extinct    847
303         florie   f  extinct    834
398         vannie   f  extinct    830
678        maebell   f  extinct    823
959          macel   f  extinct    821
1122        doshie   f  extinct    799
1074       toshiko   f  extinct    799
442       ingeborg   f  extinct    793
723         fronie   f  extinct    789
942      bettyjane   f  extinct    788
56            ceil   f  extinct    783
858         vassie   f  extinct    781
1219         nanie   f  extinct    778
339         eathel   f  extinct    763
345          clyda   f  extinct    758
1190         vicie   f  extinct    755
863           eola   f  extinct    740
193          lutie   f  extinct    735
302         leitha   f  extinct    731
153         fleeta   f  extinct    728
674          villa   f  extinct    722
713      williemae   f  extinct    722
1255        hildur   f  extinct    718
782          edris   f  extinct    706
1252          orma   f  extinct    699
829          versa   f  extinct    688
76          modena   f  extinct    683
1088         lesta   f  extinct    680
364          besse   f  extinct    671
1184          will   f  extinct    658
53            bert   f  extinct    657
201          altie   f  extinct    650
979         orlena   f  extinct    648
122       dorathea   f  extinct    645
739         lillis   f  extinct    637
459         dellie   f  extinct    634
787          lelar   f  extinct    629
509           murl   f  extinct    626
884         littie   f  extinct    623
24             tom   f  extinct    614
215         mabell   f  extinct    606
1064        girtha   f  extinct    597
401          helma   f  extinct    595
594        artelia   f  extinct    593
84            lota   f  extinct    586
160       capitola   f  extinct    579
1195         gusta   f  extinct    578
947         pinkey   f  extinct    574
323          lular   f  extinct    572
887         dellar   f  extinct    571
31          zilpha   f  extinct    570
187           cuba   f  extinct    569
1146        dossie   f  extinct    568
983          corda   f  extinct    567
1027        sister   f  extinct    563
340          cleva   f  extinct    561
452         virdie   f  extinct    555
207       permelia   f  extinct    551
1067         dewey   f  extinct    547
500      philomene   f  extinct    544
283         fronia   f  extinct    543
361         marget   f  extinct    541
210         dillie   f  extinct    537
237        almedia   f  extinct    530
277          elgie   f  extinct    529
185          manie   f  extinct    529
501         ermine   f  extinct    522
1198        vessie   f  extinct    513
334          ellar   f  extinct    511
439            ura   f  extinct    508
433          pluma   f  extinct    506
832           oral   f  extinct    506
610         mannie   f  extinct    505
378           bama   f  extinct    498
141       clotilda   f  extinct    497
1049         nobie   f  extinct    496
466         fannye   f  extinct    486
1261         eller   f  extinct    481
856          etter   f  extinct    476
393          media   f  extinct    473
164           ruie   f  extinct    470
464            exa   f  extinct    466
560         lockie   f  extinct    464
264       malissie   f  extinct    449
866         mintie   f  extinct    446
270         ethyle   f  extinct    437
632         beadie   f  extinct    435
257          fleda   f  extinct    432
620           opha   f  extinct    427
29            olie   f  extinct    420
1111        parlee   f  extinct    414
1166       shelvia   f  extinct    400
1052         hasel   f  extinct    400
510         kazuko   f  extinct    398
820          vinie   f  extinct    381
1014       noretta   f  extinct    381
1218         viney   f  extinct    377
559          oline   f  extinct    377
235       cordella   f  extinct    377
628         leaner   f  extinct    373
737          lempi   f  extinct    367
564         prudie   f  extinct    354
712          venie   f  extinct    345
630        cliffie   f  extinct    343
1188        dellia   f  extinct    339
708         liller   f  extinct    333
1194          dicy   f  extinct    328
957           beda   f  extinct    328
748          tiney   f  extinct    327
614         gillie   f  extinct    321
198      narcissus   f  extinct    318
0            elfie   f  extinct    316
597          orrie   f  extinct    313
894           effa   f  extinct    312
880         tishie   f  extinct    312
1054       alwilda   f  extinct    312
96           sinda   f  extinct    308
1134        clytie   f  extinct    301
1038          edla   f  extinct    300
1039       shelvie   f  extinct    294
117          betha   f  extinct    293
346         cyntha   f  extinct    290
640           luda   f  extinct    276
875           caro   f  extinct    269
22           lemma   f  extinct    262
718         biddie   f  extinct    262
425          litha   f  extinct    261
646           olar   f  extinct    254
1139          byrd   f  extinct    253
234          epsie   f  extinct    251
867          eppie   f  extinct    245
344       josefita   f  extinct    244
272         dezzie   f  extinct    242
533         mirtie   f  extinct    236
1098       lucindy   f  extinct    230
602           irva   f  extinct    229
1225        cannie   f  extinct    225
456         orilla   f  extinct    225
135            ica   f  extinct    223
129         hennie   f  extinct    219
962            ota   f  extinct    215
1100        manila   f  extinct    214
151         elmire   f  extinct    213
385        fronnie   f  extinct    213
706         clemie   f  extinct    211
21           ragna   f  extinct    201
593          leafy   f  extinct    197
143        pairlee   f  extinct    187
365          arkie   f  extinct    183
455         pallie   f  extinct    176
1181       octavie   f  extinct    176
1189      birdella   f  extinct    173
531         cornie   f  extinct    172
170         alzina   f  extinct    170
3             loda   f  extinct    166
239         rettie   f  extinct    163
799         clemma   f  extinct    161
377           octa   f  extinct    160
976        aurilla   f  extinct    153
1119        thursa   f  extinct    150
167          metha   f  extinct    149
666         sibbie   f  extinct    139
1035        ninnie   f  extinct    136
81            orra   f  extinct    129
710        manilla   f  extinct    124
908           bird   f  extinct    121
188         clevie   f  extinct    119
993          gunda   f  extinct    118
818           dave   f  extinct    114
719     charlottie   f  extinct    110
854         gustie   f  extinct    106
838           vicy   f  extinct    101
1149        caddie   f  extinct     96
1248      minervia   f  extinct     95
1104        grover   f  extinct     92
1125         lidie   f  extinct     91
1076        noreta   f  extinct     91
844          ethie   f  extinct     86
1018         tinie   f  extinct     83
1084         ednah   f  extinct     75
1254        rillie   f  extinct     69
1096          oney   f  extinct     61
354          dosia   f  extinct     61
1030       manerva   f  extinct     60
32           affie   f  extinct     60
1093        siddie   f  extinct     59
626      theodocia   f  extinct     54
691         lurana   f  extinct     48
966         cappie   f  extinct     41
1230          ason   f  extinct     41
682       manervia   f  extinct     40
698         neppie   f  extinct     38
471         alwine   f  extinct     25
273   francisquita   f  extinct     21
606         sannie   f  extinct     21
221         alwina   f  extinct     18
599          crete   f  extinct     14
180          franc   f  extinct     10
105         zilpah   f  extinct      9

In [61]:
pd.set_option('display.max_rows', None)
print(endangered_m_85[endangered_m_85["Rating"] == "extinct"].sort_values(by="Count", ascending=False))

           Name Sex   Rating  Count
66          fay   m  extinct   4118
949       pearl   m  extinct   3922
605      norval   m  extinct   2377
346       estel   m  extinct   2374
218    melville   m  extinct   2269
872      virgle   m  extinct   2196
1154      ewell   m  extinct   2051
833       green   m  extinct   2033
546        murl   m  extinct   1941
1109       gust   m  extinct   1871
161       verle   m  extinct   1758
1193   burdette   m  extinct   1714
780      dorris   m  extinct   1675
606     mildred   m  extinct   1583
623      buddie   m  extinct   1496
615       ethel   m  extinct   1490
1144    manford   m  extinct   1479
937       delma   m  extinct   1447
614      deward   m  extinct   1393
1217        gay   m  extinct   1382
625       rolla   m  extinct   1306
28          lem   m  extinct   1297
1033       myrl   m  extinct   1261
303     dolphus   m  extinct   1245
976     gilford   m  extinct   1225
38        mearl   m  extinct   1210
254        wash   m  extinct   1196
11        orvel   m  extinct   1157
1036     thelma   m  extinct   1142
859        guss   m  extinct   1136
952        buel   m  extinct   1135
13          alf   m  extinct   1130
1042     gussie   m  extinct   1098
214        pink   m  extinct   1089
624    williard   m  extinct   1081
217     luverne   m  extinct   1067
932        edna   m  extinct   1042
678      perley   m  extinct   1020
827      alferd   m  extinct    957
578       orvis   m  extinct    940
1048      ewald   m  extinct    922
295     clarnce   m  extinct    914
796       tomie   m  extinct    904
94        elsie   m  extinct    886
486        mont   m  extinct    884
288      burney   m  extinct    883
152      lillie   m  extinct    873
88       bertie   m  extinct    856
260        erle   m  extinct    855
908       buell   m  extinct    840
193    elsworth   m  extinct    829
920        elva   m  extinct    817
417        eino   m  extinct    814
297       elgie   m  extinct    814
185       hideo   m  extinct    805
9          burr   m  extinct    803
1120     gurney   m  extinct    790
1058     minnie   m  extinct    787
343     woodroe   m  extinct    784
791      mattie   m  extinct    780
639     pauline   m  extinct    775
470         ida   m  extinct    766
192     hubbard   m  extinct    763
895      selmer   m  extinct    759
929       dixie   m  extinct    752
187     lucille   m  extinct    750
744        osie   m  extinct    748
518      bessie   m  extinct    737
1171      buren   m  extinct    734
670       othel   m  extinct    732
123      bascom   m  extinct    731
523      worley   m  extinct    730
969        opal   m  extinct    718
55        clide   m  extinct    718
860     lilburn   m  extinct    713
1145       byrd   m  extinct    709
279     pearlie   m  extinct    699
1094       ferd   m  extinct    689
731      minoru   m  extinct    675
1240     ruffus   m  extinct    674
589      virgie   m  extinct    668
633    elbridge   m  extinct    659
323      hardie   m  extinct    644
690      barnie   m  extinct    641
1077    hurbert   m  extinct    640
339       duard   m  extinct    632
772    pleasant   m  extinct    629
90          ola   m  extinct    624
857      almond   m  extinct    617
255        rube   m  extinct    612
592       ottie   m  extinct    609
452        harl   m  extinct    601
819    pershing   m  extinct    599
763      delmus   m  extinct    599
594      orange   m  extinct    598
710        odus   m  extinct    596
1004     nellie   m  extinct    593
321    guilford   m  extinct    589
460    hansford   m  extinct    587
829      earley   m  extinct    581
393      asbury   m  extinct    579
389      seward   m  extinct    568
277    gertrude   m  extinct    568
741      tollie   m  extinct    566
870       harve   m  extinct    554
905         irl   m  extinct    554
1106     estell   m  extinct    551
1129       dora   m  extinct    550
19        lisle   m  extinct    543
467     lillard   m  extinct    541
803      hester   m  extinct    537
1113      toivo   m  extinct    535
440     pinkney   m  extinct    531
529       elige   m  extinct    528
619         ova   m  extinct    528
524       verna   m  extinct    525
312       metro   m  extinct    522
627       arbie   m  extinct    513
18         kaye   m  extinct    503
228     hillery   m  extinct    501
941      myrtle   m  extinct    498
456      hattie   m  extinct    494
178         lum   m  extinct    493
1056    adelard   m  extinct    488
1174    fremont   m  extinct    482
79         erby   m  extinct    480
837      erland   m  extinct    478
770        robt   m  extinct    468
223    burleigh   m  extinct    467
355       agnes   m  extinct    465
253       orley   m  extinct    459
502     plummer   m  extinct    453
581        watt   m  extinct    444
761       alvia   m  extinct    441
34      fayette   m  extinct    438
590       viola   m  extinct    434
479       eliga   m  extinct    434
372     thurlow   m  extinct    422
484    albertus   m  extinct    421
60     clemence   m  extinct    418
135      harrie   m  extinct    417
775       aloys   m  extinct    414
760   blanchard   m  extinct    413
1190      mabel   m  extinct    409
1023    erastus   m  extinct    407
966      hughey   m  extinct    405
1022     cleave   m  extinct    403
1047       vera   m  extinct    398
1234      posey   m  extinct    396
1076       elzy   m  extinct    396
376         con   m  extinct    389
477        ples   m  extinct    388
98       doctor   m  extinct    379
935      vollie   m  extinct    378
802        oley   m  extinct    373
773    coolidge   m  extinct    372
392      fannie   m  extinct    369
911   commodore   m  extinct    368
867       claus   m  extinct    366
892      robley   m  extinct    362
507      dozier   m  extinct    361
220     amerigo   m  extinct    359
917       donat   m  extinct    351
5         waino   m  extinct    347
283        babe   m  extinct    345
1075      oddie   m  extinct    343
450        mell   m  extinct    342
1010     wilkie   m  extinct    340
1034     burrel   m  extinct    339
475        lula   m  extinct    339
898        eula   m  extinct    332
1096      abbie   m  extinct    330
787     needham   m  extinct    328
317        lena   m  extinct    326
611     asberry   m  extinct    323
58         floy   m  extinct    323
194    gottlieb   m  extinct    320
979        harm   m  extinct    320
990      lovett   m  extinct    319
1203      ebbie   m  extinct    317
533       esker   m  extinct    313
1229  littleton   m  extinct    312
607        derl   m  extinct    306
424         oda   m  extinct    301
512       leona   m  extinct    294
964     bluford   m  extinct    293
842        rice   m  extinct    287
734        orla   m  extinct    286
1001       wirt   m  extinct    286
464       hymen   m  extinct    285
230        less   m  extinct    281
1200      susie   m  extinct    278
170       mamie   m  extinct    278
268        lola   m  extinct    275
522       miner   m  extinct    274
311       oland   m  extinct    274
17         birt   m  extinct    268
683     council   m  extinct    263
184         ebb   m  extinct    247
712      hezzie   m  extinct    247
648        flem   m  extinct    244
832       effie   m  extinct    241
916       press   m  extinct    241
641       ovila   m  extinct    240
408      winnie   m  extinct    228
736     blanche   m  extinct    223
423       bynum   m  extinct    223
854      tatsuo   m  extinct    222
7        beulah   m  extinct    213
1079    hjalmer   m  extinct    202
21       jettie   m  extinct    197
788       alcee   m  extinct    182
412     pearley   m  extinct    178
1181  ethelbert   m  extinct    178
527       genie   m  extinct    173
1031      flora   m  extinct    172
1067       thos   m  extinct    166
1134      fleet   m  extinct    166
1208     ignatz   m  extinct    158
714       offie   m  extinct    151
653         ell   m  extinct    144
1011      almus   m  extinct    143
472       della   m  extinct    139
679       shoji   m  extinct    134
713         sie   m  extinct    133
811       maude   m  extinct    133
42        ewart   m  extinct    131
963        dorr   m  extinct    124
482       grove   m  extinct    124
36       greene   m  extinct    121
795       alver   m  extinct    119
757     shafter   m  extinct    119
402       fount   m  extinct    118
281        alta   m  extinct    117
493      emmons   m  extinct    117
167     delphin   m  extinct    116
825        ewin   m  extinct    115
923     hjalmar   m  extinct    115
942       elick   m  extinct    113
200      ambers   m  extinct    113
1006     tallie   m  extinct    112
915        bird   m  extinct    109
1063       alba   m  extinct    108
1222       olof   m  extinct    107
45         dink   m  extinct    107
754      lizzie   m  extinct    102
742         add   m  extinct    102
1066       math   m  extinct    100
1214       atha   m  extinct     99
1098        abb   m  extinct     96
779     alphons   m  extinct     90
558      ceylon   m  extinct     86
563         ott   m  extinct     84
1062       purl   m  extinct     81
395        polk   m  extinct     80
270      friend   m  extinct     74
49           ah   m  extinct     74
1221        obe   m  extinct     73
62          fed   m  extinct     72
823      goebel   m  extinct     70
1220       foch   m  extinct     67
971       hence   m  extinct     66
516     hosteen   m  extinct     65
1068     boysie   m  extinct     63
1086    benjman   m  extinct     58
1039   thorwald   m  extinct     54
1007      algot   m  extinct     53
162      severt   m  extinct     53
1110      virge   m  extinct     52
970        arba   m  extinct     47
939       clabe   m  extinct     45
570       amasa   m  extinct     37
302        maud   m  extinct     31
371         lim   m  extinct     30
134         ham   m  extinct     29
618         nim   m  extinct     28
394        esta   m  extinct     27
767        lish   m  extinct     24
889        doll   m  extinct     24
1210       bose   m  extinct     20
544       rhoda   m  extinct     12
1164       lone   m  extinct     11
1021       bunk   m  extinct     10
476      schley   m  extinct     10
739         edw   m  extinct      6
1149       roll   m  extinct      5